- Cesium3DTiles/src/Tileset.cpp
- CesiumGltfReader/src/Reader.cpp
- Some error messages mentioned a `Tileset`, although they referred to a `Tile`
- The error messages in the glTF `Reader` class have been extended, generally from "Something is wrong" to "This-and-that is wrong" (e.g. printing actual and expected values or actual sizes and limits)
> Updated and extended error messages

- CHANGES.md
- Cesium3DTiles/src/QuantizedMeshContent.cpp
Gave glTFs created from quantized-mesh terrain tiles a more sensible material with a `metallicFactor` of 0.0 and a `roughnessFactor` of 1.0. Previously the default glTF material was used, which has a `metallicFactor` of 1.0, leading to an undesirable appearance.
Also added `CHANGES.md`.
In Cesium for Unreal, before this PR (not shininess at the horizon, starting where the photogrammetry ends):
After this PR (no more shininess):
> Assign a better material for quantized-mesh tiles.

- CHANGES.md
- Cesium3DTiles/include/Cesium3DTiles/RasterOverlayTileProvider.h
- Cesium3DTiles/src/BingMapsRasterOverlay.cpp
- Cesium3DTiles/src/RasterOverlayTileProvider.cpp
- CesiumGltf/include/CesiumGltf/ImageCesium.h
`BingMapsRasterOverlay` purposely requests that the Bing servers return a zero-length image for non-existent tiles. That's what the `n=z` query parameter does. So we shouldn't report these zero-length images as a problem.
> Don't always report zero-length images as errors.

- CHANGES.md
- Cesium3DTiles/src/Tileset.cpp
Report in the forum https://community.cesium.com/t/lod-problems-with-photogrammetry-model/12861. 
The spec currently says tile.transform should not apply to geometric error, but it seems to be a bug on the specs. It was mentioned [here](https://github.com/CesiumGS/3d-tiles/issues/367). Also cesiumJS already applied the transform's scale component to the geometric error as well
> Scale geometric error with tile transform

- .travis.yml
- Cesium3DTiles/src/BingMapsRasterOverlay.cpp
As suggested in https://github.com/CesiumGS/cesium-native/pull/227#issuecomment-828201482 , the call in `BingMapsRasterOverlay::createTileProvider` that callled `CreditSystem::createCredit` has been moved from the worker thread to the main thread.
As a ... (hacky? or pragmatic?) ... well, as a "layer of validation", I added some 
```
std::string currentThreadString() {
std::ostringstream ss;  
ss << std::this_thread::get_id();
return ss.str();
}
Credit CreditSystem::createCredit(const std::string& html) {
SPDLOG_WARN("Called createCredit on {}", currentThreadString());
```
(and to all other functions of `CreditSystem`), and indeed, *most* functions had been called by the same thread *most* of the time, *except* for that few `createCredit` calls. After this change, **all** calls to the …
> Moved credit creation into main thread

- .travis.yml
Following the advice here:
https://travis-ci.community/t/clang-10-was-recently-broken-on-linux-unmet-dependencies-for-clang-10-clang-tidy-10-valgrind/11527
> Fix Clang build on Travis.

- CesiumGltfWriter/src/AccessorSparseWriter.cpp
- CesiumGltfWriter/src/AccessorWriter.cpp
- CesiumGltfWriter/src/AnimationWriter.cpp
- CesiumGltfWriter/src/AssetWriter.cpp
- CesiumGltfWriter/src/BufferViewWriter.cpp
- CesiumGltfWriter/src/BufferWriter.cpp
- CesiumGltfWriter/src/CameraWriter.cpp
- CesiumGltfWriter/src/ExtensionWriter.cpp
- CesiumGltfWriter/src/ImageWriter.cpp
- CesiumGltfWriter/src/JsonObjectWriter.cpp
- CesiumGltfWriter/src/JsonObjectWriter.h
- CesiumGltfWriter/src/MaterialWriter.cpp
- CesiumGltfWriter/src/MeshWriter.cpp
- CesiumGltfWriter/src/NodeWriter.cpp
- CesiumGltfWriter/src/SamplerWriter.cpp
- CesiumGltfWriter/src/SceneWriter.cpp
- CesiumGltfWriter/src/SkinWriter.cpp
- CesiumGltfWriter/src/TextureWriter.cpp
- CesiumGltfWriter/test/TestJsonObjectWriter.cpp
This parmaeter is ultimately unnecessary. The caller should be responsible
for ensuring that the CesiumGltf::JsonWriter state is balanced before calling
writeJsonValue. This should simplify our internal API.
> Remove redundant `hasRootObject` from writeJsonValue

- CesiumGltf/include/CesiumGltf/AccessorSpec.h
- CesiumGltf/include/CesiumGltf/BufferSpec.h
- CesiumGltf/include/CesiumGltf/ImageSpec.h
- CesiumGltf/include/CesiumGltf/ModelSpec.h
The only changes are to incorrectly-wrapped comments, now that comments no longer get incorrectly wrapped. I'm going to insta-merge this because it's super trivial.
> Regenerate glTF classes and re-run the formatter.

- CesiumGltfReader/src/GltfReader.cpp
`pImage` isn't being freed after being copied. This fixes that leak: We're running into out of memory crashes without it :grimacing:
> Fix memory leak in GltfReader.cpp

- CHANGES.md
- Cesium3DTiles/src/RasterOverlay.cpp
Explicitly set `RasterOverlayProvider` owned by `RasterOverlay` to be `nullptr` instead of letting `unique_ptr` destructor get called implicitly. If we let `unique_ptr()` destructor called implicitly, `_pTileProvider` will get destructed first, but it will never set to be `nullptr`. So when `_pPlaceholder` is destroyed, its `_pPlaceholder` tile and _tiles member destructor will retrieve _pTileProvider instead of _pPlaceholder and it crashes
> Fix development package crash when shut down

- CHANGES.md
- CesiumGltf/include/CesiumGltf/AccessorView.h
- CesiumGltf/test/TestAccessorView.cpp
`createAccessorView` is a handy way to create an `AccessorView` for a glTF `Accessor` of unknown `type` and `componentType`, and dispatch it a function with overloads for each type. You can even use a template to capture some of the possible accessor types. Since C++14 (I think), you can use `auto` in a lambda to effectively create a template. But unfortunately it was hard to use such a generic lambda with `createAccessorView` because, on error (e.g. the Accessor's `componentType` isn't valid at all), `createAccessorView` would create an `AccessorView<nullptr_t>`. nullptr_t isn't a normal numeric type, so it was somewhere between impossible and a huge hassle to write generic code that would work with both numeric types and with nullptr_t.
So this PR changes `createAccessorView` to instead …
> Allow use of createAccessorView with a simple lambda.

- extern/CMakeLists.txt
Possibly fixes: #251. 
Tells `cpp-httplib` not to look for zlib or openssl. Quoting @baothientran for what the issue may have been:
>hm good chance is your dev environment have zlib and openssl installed and httplib link against them when building. But those libraries are not copied in to unreal third party and it didn't know how to link against those symbol 
I'm not going to pretend I understand cmake or what exactly httplib, zlib, and openssl do, but this change finally solved a very painful issue I was stuck on for the last two days :). The issue does not happen in everybody's dev environment, so I think Bao's idea makes a lot of sense. 
@jtorresfabra @kring
> Cmake fix for cpp-httplib

- CHANGES.md
- CMakeLists.txt
- CesiumAsync/CMakeLists.txt
- CesiumAsync/include/CesiumAsync/SqliteCache.h
- CesiumAsync/src/SqliteCache.cpp
- extern/CMakeLists.txt
- extern/sqlite3/CMakeLists.txt
- extern/sqlite3/cesium-sqlite3.h
- extern/sqlite3/sqlite3.h
This helps us avoid a conflict with other sqlite implementations, notably the limited one built into Unreal Engine.
The way it works is by, at configure time, reading sqlite3.c and sqlite3.h, doing a search/replace of `sqlite3` with `cesium_sqlite3`, and writing the output to the build directory. The rewritten files are then added as the sqlite3 target's source and include files. They're written using `file(GENERATE OUTPUT ...)` so they won't be rewritten (and thus recompiled) unless they actually change.
Now in our code, we wrap all use of SQLite symbols in a macro, `CESIUM_SQLITE`, defined in `cesium-sqlite3.h`, which prefixes the symbol with `cesium_` only if the build is configured to rename the sqlite symbols. The end result is a configure-time selection of whether to privatize the …
> Add an option to prefix all sqlite3 symbols with `cesium_`

- CesiumGeometry/include/CesiumGeometry/QuadtreeTileID.h
File `CesiumGeometry/include/CesiumGeometry/QuadtreeTileID.h` misses <cstdint> to use `uint32_t`. So I add this line.
```c++
#include <cstdint>
```
> fix: missing includes cstdint

- Cesium3DTiles/include/Cesium3DTiles/RasterOverlay.h
- Cesium3DTiles/include/Cesium3DTiles/RasterOverlayTileProvider.h
There are two small problems in `Cesium3DTiles/include/Cesium3DTiles/RasterOverlayTileProvider.h`:
1. `Cesium3DTiles::RasterOverlayTileProvider::_throttledTilesCurrentlyLoading` is int32_t but its get() function return uint32_t, so I change 3 associated variables.
2. `Function Cesium3DTiles::RasterOverlayTileProvider::getCredit()` return a `const std::optional<Credit>` and this cause clang-tidy reports ['const' at top level, which may reduce code readability without improving const correctness](https://stackoverflow.com/questions/63972019/understanding-const-at-top-level-which-may-reduce-code-readability-without-i). Just need to add '&'.
> Use uint32_t instand of int32_t as count of tiles and use const T& not const T

- Cesium3DTiles/test/TestCreditSystem.cpp
- Cesium3DTiles/test/TestQuantizedMeshContent.cpp
- Cesium3DTiles/test/TestSkirtMeshMetadata.cpp
- Cesium3DTiles/test/TestTilesetSelectionAlgorithm.cpp
- Cesium3DTiles/test/TestUpsampleGltfForRasterOverlay.cpp
- CesiumAsync/test/TestCacheAssetAccessor.cpp
- CesiumAsync/test/TestDiskCache.cpp
- CesiumAsync/test/TestInternalTimegm.cpp
- CesiumAsync/test/TestResponseCacheControl.cpp
- CesiumGeometry/test/TestAxisTransforms.cpp
- CesiumGeometry/test/TestBoundingSphere.cpp
- CesiumGeometry/test/TestClipTriangleAtAxisAlignedThreshold.cpp
- CesiumGeometry/test/TestIntersectionTests.cpp
- CesiumGeometry/test/TestOrientedBoundingBox.cpp
- CesiumGeometry/test/TestPlane.cpp
- CesiumGeometry/test/TestRectangle.cpp
- CesiumGeospatial/test/TestBoundingRegion.cpp
- CesiumGeospatial/test/TestGlobeRectangle.cpp
- CesiumGltf/test/TestAccessorView.cpp
- CesiumGltf/test/TestJsonValue.cpp
- CesiumGltfReader/test/TestReader.cpp
- CesiumGltfWriter/test/TestWriter.cpp
- CesiumNativeTests/src/test-main.cpp
- CesiumUtility/test/TestDoublyLinkedList.cpp
- CesiumUtility/test/TestMath.cpp
We were using quotes instead of angle brackets to #include catch2. So this trivial PR just changes it to angle brackets, consistent with all the other third party libraries.
> Use angle brackets to #include catch2.

- CHANGES.md
- CMakeLists.txt
This PR adds a cmake option to enable or disable code coverage. I also removed the "cesium-native-is-submodule" check because it didn't seem to be working, plus there's no need for it now that you can enabled or disable manually
> CMake option for code coverage

- CHANGES.md
- Cesium3DTiles/src/upgradeBatchTableToFeatureMetadata.cpp
After merging #281, I found some small things to fix:
* Don't interpret `extras` or `extensions` as property names, because they're special. Without this change, Cesium for Unreal was throwing assertion failures and log messages when loading Cesium OSM Buildings.
* Add performance tracing to `upgradeBatchTableToFeatureMetadata` (the time spent in there is very reasonable).
* Updated CHANGES.md.
> Metadata tweaks

- CesiumGltf/include/CesiumGltf/MetadataArrayView.h
- CesiumGltf/include/CesiumGltf/MetadataPropertyView.h
- CesiumGltf/include/CesiumGltf/PropertyType.h
- CesiumGltf/include/CesiumGltf/PropertyTypeTraits.h
Some small changes to the metadata system to support CesiumGS/cesium-unreal#545:
* Add default constructors for `MetadataPropertyView` and `MetadataArrayView`, to reduce the need for std::monostate. You can think of these as views on invalid properties and empty arrays, respectively.
* Added `IsMetadataInteger<T>` and `IsMetadataFloat<T>` to distinguish between the two types of numeric properties.
* Make the `PropertyType` enum not a bitmask, because it's not used as one and as a bitmask it won't fit into a uint8, which is required by Unreal Blueprints enums.
> Default constructors for views, IsMetadataInteger/Floating.

- CHANGES.md
- CesiumAsync/include/CesiumAsync/AsyncSystem.h
- CesiumAsync/include/CesiumAsync/Future.h
- CesiumAsync/test/TestAsyncSystem.cpp
Builds on #277 so merge that first.
`all` is needed for #252, and is also likely to be used for i3dm support. `catchImmediately` is useful for the tests.
> Add `AsyncSystem::all` and `Future<T>::catchImmediately`

- Cesium3DTilesSelection/src/GltfContent.cpp
- Cesium3DTilesSelection/src/QuantizedMeshContent.cpp
We add an extra to loaded glTFs indicating the URL they were loaded from, `Cesium3DTiles_TileUrl`, which is really handy for debugging. But in #301 it was accidentally renamed to `Cesium3DTilesSelection_TileUrl`. This PR changes it back, so double-clicking tiles in Unreal Engine tells you their URL again.
> Fix tile URL "extra" in glTFs.

- .travis.yml
All Linux builds in all branches are currently failing. For example:
https://app.travis-ci.com/github/CesiumGS/cesium-native/jobs/532894339
The error is:
```
Err:5 https://packages.erlang-solutions.com/ubuntu focal Release
Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 13.32.214.118 443]
```
So some random third party package source used by Ubuntu Focal on Travis has an expired certificate and it's breaking all our builds. Nice. Turns out this is rabbitmq.list and we don't need it, so I've removed it.
> Fix travis build failures on Linux caused by an expired PPA certificate

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TilesetExternals.h
I _think_ the `AsyncSystem.h` has to be included in the `TilesetExternals`, because it is a (non-pointer, non-reference) member.
> Added missing include of AsyncSystem in TilesetExternals

- CHANGES.md
- Cesium3DTilesSelection/src/BingMapsRasterOverlay.cpp
- Cesium3DTilesSelection/src/RasterOverlayTileProvider.cpp
- CesiumGeometry/include/CesiumGeometry/Rectangle.h
- CesiumGeometry/src/Rectangle.cpp
- CesiumGeometry/test/TestRectangle.cpp
- CesiumGeospatial/include/CesiumGeospatial/GlobeRectangle.h
- CesiumGeospatial/src/GlobeRectangle.cpp
This is a small PR broken out of #252.
* Added `Rectangle::computeUnion` (we can't call it `union` because that's a C++ reserved word).
* Renamed `Rectangle::intersect` and `GlobeRectangle::intersect` to `computeIntersection` (to match).
> Add Rectangle::computeUnion method and rename intersect to match

- CHANGES.md
- CesiumGltfWriter/src/MaterialWriter.cpp
According to [the specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-material), the property name for the normal texture should be `normalTexture` (its *type* is called `normalTextureInfo`, but not the property).
This caused a validation error 
UNEXPECTED_PROPERTY | Unexpected property. | /materials/0/normalTextureInfo
for assets that contained a normal texture.
This PR just fixes that property name.
> Fixed property name of normal texture info

- Cesium3DTilesSelection/src/GltfContent.cpp
As mentioned in https://github.com/CesiumGS/cesium-native/commit/acd276388a4bda5426ddb72d2fd17c18241c7ab9#r55708457  (and earlier, but apparently, the comment was overlooked)
> Raster overlay refactoring fix compiler error

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TileContentLoadResult.h
- Cesium3DTilesSelection/src/Tile.cpp
Fixes CesiumGS/cesium-unreal#612
It works like this:
- When generating overlay texture coordinates, also store the corresponding Projections in the `TileContentLoadResult`.
- When replacing a placeholder tile with real tiles, check if we have the right texture coordinates for the provider's projection. If not, force the tile to reload. We could definitely do a more surgical update here in the future.
> Detect missing overlay textures coordinates and add them.

- CesiumAsync/src/ResponseCacheControl.cpp
When building with `_GLIBCXX_DEBUG` the output is:
```
cmake -B build -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_FLAGS_DEBUG=-D_GLIBCXX_DEBUG && cmake --build build --parallel 8
```
```
Scanning dependencies of target CesiumAsync
[ 71%] Building CXX object CesiumAsync/CMakeFiles/CesiumAsync.dir/src/AsyncSystem.cpp.o
[ 71%] Building CXX object CesiumAsync/CMakeFiles/CesiumAsync.dir/src/CachingAssetAccessor.cpp.o
[ 71%] Building CXX object CesiumAsync/CMakeFiles/CesiumAsync.dir/src/HttpHeaders.cpp.o
[ 72%] Building CXX object CesiumAsync/CMakeFiles/CesiumAsync.dir/src/InternalTimegm.cpp.o
[ 72%] Building CXX object CesiumAsync/CMakeFiles/CesiumAsync.dir/src/QueuedScheduler.cpp.o
[ 72%] Building CXX object CesiumAsync/CMakeFiles/CesiumAsync.dir/src/ResponseCacheControl.cpp.o …
```
> Fix build with _GLIBCXX_DEBUG

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tile.h
- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/test/TestTilesetSelectionAlgorithm.cpp
There was an issue (may or may not be related to [this issue](https://github.com/CesiumGS/cesium-unreal/issues/440)) where enabling "Forbid Holes" completely broke the loading of CWT and probably any other tileset. To reproduce simply load up CWT, check "Forbid Holes", and refresh the tileset.
Why I think it was happening:
Children are initially not considered "renderable" so the parent tile refuses to refine.  I've seen the children have placeholder loading raster tiles (not mapped yet) and I've seen the children have loaded raster tiles that weren't yet put into the ready slot. In both cases they're considered not renderable so the parent does not refine. While the parent is waiting, `Tile::loadContent` gets called on the children, but there is never a `Tile::update` call and so …
> Fix for "Forbid Holes" not working

- CHANGES.md
- Cesium3DTilesSelection/src/Batched3DModelContent.cpp
Fixes problems with the "Washington State" tileset, ion asset ID 55416.
Much to my surprise, RapidJSON's `IsDouble` returns false for integers, even though `GetDouble` works and performs the expected conversion, and `IsInt64` returns true for a 32-bit integer. So in the problem tileset, one of the RTC_CENTER coordinate values happened to have an integer value, and so `IsDouble` was returning false, and so we were assuming the RTC_CENTER value was invalid and ignoring it, and so the tileset was rendered in the wrong place.
This PR checks for _any_ number and then converts it to a double.
CC @argallegos @nithinp7
> Don't ignore RTC_CENTER when it has an integer coordinate value.

- Cesium3DTilesSelection/test/TestUpgradeBatchTableToExtFeatureMetadata.cpp
- CesiumGltf/include/CesiumGltf/ClassProperty.h
- CesiumGltf/include/CesiumGltf/Enum.h
- CesiumGltf/include/CesiumGltf/FeatureTableProperty.h
- CesiumGltf/include/CesiumGltf/MetadataFeatureTableView.h
- CesiumGltf/include/CesiumGltf/ModelEXT_feature_metadata.h
- CesiumGltf/src/MetadataFeatureTableView.cpp
- CesiumGltf/src/PropertyType.cpp
- CesiumGltf/test/TestMetadataFeatureTableView.cpp
- CesiumGltf/test/TestPropertyType.cpp
- CesiumGltfReader/generated/ClassPropertyJsonHandler.h
- tools/generate-classes/glTF.json
After cleaning up the `EXT_feature_metadata` schema in https://github.com/CesiumGS/glTF/pull/29 there were a few good changes that the code generator picked up - `Type`, `ComponentType`, and `OffsetType` are now "real" types instead of `CesiumUtility::JsonValue`. Updated the code to use these types instead of hardcoded strings.
> Regenerate classes for EXT_feature_metadata

- CesiumAsync/test/TestCacheAssetAccessor.cpp
This timestamp seems to have been arbitrarily chosen, but tests have been failing since 3:28am this morning since that timestamp is now in the past.
> Fix CacheAssetAccessor test

- CHANGES.md
- CesiumGltf/include/CesiumGltf/FeatureTexture.h
- CesiumGltfReader/generated/GeneratedJsonHandlers.cpp
- tools/generate-classes/generate.js
- tools/generate-classes/resolveProperty.js
Properties with names that are reserved C++ keywords are appended with "Property" so that they do not cause issues in the C++ GltfReader code. But when actually parsing a gltf we should check the JSON for the original string, even if it is a C++ keyword.
> Fixes handling of reserved c++ keywords in gltf reader generator

- CMakeLists.txt
- Cesium3DTilesSelection/src/BoundingVolume.cpp
- Cesium3DTilesSelection/src/GltfContent.cpp
- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/upsampleGltfForRasterOverlays.cpp
- CesiumGeometry/test/TestOrientedBoundingBox.cpp
- CesiumGeospatial/src/EllipsoidTangentPlane.cpp
The [GLM manual](https://github.com/g-truc/glm/blob/master/manual.md#section2) has some defines we can set to make GLM more strict and hopefully avoid bugs:
```
GLM_FORCE_XYZW_ONLY # Disable .rgba and .stpq to make it easier to view values from debugger
GLM_FORCE_EXPLICIT_CTOR # Disallow implicit conversions between dvec3 <-> dvec4, dvec3 <-> fvec3, etc
GLM_FORCE_SIZE_T_LENGTH # Make vec.length() and vec[idx] use size_t instead of int
```
I was also thinking about adding `GLM_FORCE_INLINE` but there was a compilation failure in one of the unit tests where the GLM function could not be inlined. I haven't checked if `GLM_FORCE_INLINE` has any runtime improvement so it could be worth looking into some other time.
> Added stricter GLM defines

- CesiumJsonReader/src/JsonReader.cpp
This PR fixes two precision problems with the JSON readers/writers. My setup is a round trip from glTF to JSON to glTF to JSON.
Old behavior:
`0.20116522777145346` - original number that's perfectly representable as float64
`0.20116522777145347` - string that's stored in the JSON
`0.2011652277714535` - value that's parsed from JSON
New behavior:
`0.20116522777145346` - original number that's perfectly representable as float64
`0.20116522777145346` - string that's stored in the JSON
`0.20116522777145346` - value that's parsed from JSON
1) Adding `kParseFullPrecisionFlag` makes it parse as `0.20116522777145346` instead of `0.2011652277714535` :heavy_check_mark: 
2) The newest version of rapidjson stores `0.20116522777145346` instead of `0.20116522777145347` in JSON. Even though these two …
> Improve precision when using rapidjson

- CesiumGltfReader/src/decodeDraco.cpp
i think accessor offset value should set to 0, because we create a new bufferview and buffer.
> set indices accessor offset value to 0 after decode draco mesh

- .travis.yml
- Cesium3DTilesSelection/test/TestUpgradeBatchTableToExtFeatureMetadata.cpp
- CesiumAsync/test/TestAsyncSystem.cpp
- CesiumAsync/test/TestCacheAssetAccessor.cpp
- package-lock.json
Fixes #394 
I think the problem is that `operator[]` for `std::vector<bool>` doesn't return an actual bool on this platform, but rather something that can be implicitly converted to bool. When we pass that thing to RapidJSON's PushBack, it still doesn't get implicitly converted to a bool. So the JSON ends up incorrect. Fixed by explicitly casting return return value of `operator[]` to the right type.
> Fix macOS test failures.

- CesiumJsonWriter/src/PrettyJsonWriter.cpp
Thoughts on changing the default indentation from 4 spaces to 2 spaces for the glTF writer?
> Use 2 space indentation for glTF writer

- .gitmodules
There's no `extern/glTF` folder when cesium-native is cloned. The submodule seems to have been removed everywhere except in `.gitmodules`.
> Remove unused KhronosGroup/glTF submodule

- CHANGES.md
- Cesium3DTilesSelection/src/Tileset.cpp
We forget to notify tile done loading when ion response can't be parsed, which makes the tileset unable to be destructed
> Notify tile done loading when ion response can't be parsed

- CHANGES.md
- CesiumAsync/include/CesiumAsync/Impl/WithTracing.h
- CesiumAsync/include/CesiumAsync/Impl/unwrapFuture.h
Previously this would result in a compiler error.
Builds on #422 so merge that first.
> Allow a continuation attached to a SharedFuture to return a Future (rather than a normal value)

- CHANGES.md
- CesiumGeometry/include/CesiumGeometry/BoundingSphere.h
- CesiumGeometry/src/BoundingSphere.cpp
- CesiumGeometry/test/TestBoundingSphere.cpp
Fixes #288. It looks like the original function computed the estimated squared distance so possibly we could move it to a seperate function for performance. I also added that it will return zero if the point is inside the sphere.
> fix distance squared to function in bounding sphere

- extern/CMakeLists.txt
The recently-added KTX-Software library slams the value `11.0` into `CMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET`, causing all cesium-native libraries to be built targeting iOS 11. This won't work because cesium-native uses some `std::variant` features that apparently require iOS 12. This PR overrides the value set by KTX.
> Don't let KTX force us to target iOS 11

- CHANGES.md
- CesiumAsync/include/CesiumAsync/Promise.h
Fix the issue where CesiumAsync failed to compile when passing lvalue reference to Promise::resolve()
> Add Promise::resolve(const T&)

- CHANGES.md
- Cesium3DTilesSelection/src/Tileset.cpp
This PR fixes the bug where the Cesium CWT would not load if the Forbid Holes option was enabled.
> Fix forbid holes bug

- Cesium3DTilesSelection/src/Tile.cpp
Fixes a largely inconsequential bug that I ran across the other day.
> Fix how Tile::computeByteSize handles external images

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/IonRasterOverlay.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/IonRasterOverlay.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
Because we should mostly avoid unsigned types, and because 32-bits for Cesium ion asset IDs might someday be insufficient.
> Use int64_t instead of uint32_t for Cesium ion asset IDs.

- CHANGES.md
- Cesium3DTilesSelection/src/IonRasterOverlay.cpp
Fixes a bug that prevents accessing TMS layers from Cesium ion.
`JsonHelpers::getStringOrDefault(response, "accessToken")` tries to interpret `response` as a string and returns `"accessToken"` if that fails. `JsonHelpers::getStringOrDefault(response, "accessToken", "")` tries to interpret a property called `accessToken` on the response object as a string, and returns an empty string if that fails. Clearly the API could be better here.
> Get ion token correctly for TMS.

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/ExternalTilesetContent.cpp
- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
This PR has a few significant improvements to tile selection, especially when "Forbid Holes" is enabled:
When "Forbid Holes" is enabled, all of a parent tile's children must be loaded before the parent can be refined. This forces us to "refine down through the tree." But previously (before this PR), the algorithm _also_ loaded all children of a tile that met the SSE. That was super wasteful; in a quadtree it would end up loading 4x more tiles than necessary! "Forbid Holes" enabled is always going to be slower, but now it's much closer to peformance parity and therefore much more useable.
With "Forbid Holes" enabled, the algorithm would often get stuck in a cycle of loading and unloading the same tiles repeatedly. 😱  This PR fixes it.
Essentially the problem was that already-loaded child …
> Less holes, and improvements to "forbid holes" mode

- CHANGES.md
- CesiumAsync/include/CesiumAsync/SqliteCache.h
- CesiumAsync/src/SqliteCache.cpp
In my case, when reading from `requestHeader`, the JSON string was empty, which caused the json document to have a parse error, and then the program would crash.
Now, it does not crash, it will query from the network instead, and attempt to store the value again. In my case, the value cannot be stored because the sqlite database became corrupt.
If SQL_STATUS is ever SQL_CORRUPT after a SQL_Step command, then it will attempt to delete the file, and then create the database again.
I was unable to call `destroyDatabase` during the `getEntry` because it is marked `const`.
> Fix sqlite crash

- CHANGES.md
- Cesium3DTilesSelection/src/Tile.cpp
Previously, we called `IPrepareRendererResources::prepareInMainThread` _before_ we updated the `Tile` with the loaded content. Mostly this doesn't matter, but if `prepareInMainThread` used the tile's bounding volume, for example, and the loaded content included an updated bounding volume, this would result in `prepareInMainThread` using a stale bounding volume. Better to do the update first.
> Update Tile from Content before calling prepareInMainThread

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/ImplicitTraversal.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TileContext.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/ImplicitTraversal.cpp
- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetLoadTileFromJson.cpp
- Cesium3DTilesSelection/src/TilesetLoadTilesetDotJson.cpp
- Cesium3DTilesSelection/test/TestQuantizedMeshContent.cpp
This is a PR into #485.
In the process of writing https://github.com/CesiumGS/cesium-native/blob/main/doc/implicit-tiling.md, I realized there might be a pretty straightforward way to make sure all of the necessary availability tiles are loaded. This PR is an attempt to implement it, and I think it worked out ok. @joseph-kaile please take a look, and if you're happy you can merge both this PR and #485. Let me know if you have any concerns.
The basic idea here is that whenever we're loading a quadtree tile, consider whether that tile is also an "availability tile" in any layers. If it is, download that layer's version of the tile and add its availability data to the TileContext. And make these extra loads prerequisites for moving the tile into the `ContentLoaded` state. Because we never …
> Make quantized-mesh availability tile loading part of the tile content load process

- CHANGES.md
- Cesium3DTilesSelection/src/Tileset.cpp
@nithinp7 and @argallegos noticed recently that the New York City Buildings tileset in level 6 of the Cesium for Unreal Samples would sometimes get stuck. Tiles would be missing, no matter how long you wait. Moving the camera arounda  bit would usually fix it.
The problem turned out to be the tile selection's "kick" mechanism. It's usually a good idea to skip as many levels of detail as possible, and just directly load the tiles we need for the current view. But sometimes that's a very large number of tiles, and the user would have to sit there a long time waiting for them all. Our selection algorithm detects how many descendants of a given tile are waiting to load, and if it's a lot (a user-defined number), it kicks them all out of the load queue and instead loads and renders the current …
> Don't kick external tileset children.

- .vscode/settings.json
- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterizedPolygonsOverlay.h
- Cesium3DTilesSelection/src/RasterizedPolygonsOverlay.cpp
- Cesium3DTilesSelection/src/RasterizedPolygonsTileExcluder.cpp
- Cesium3DTilesSelection/src/TileUtilities.cpp
- Cesium3DTilesSelection/src/TileUtilities.h
Adds an option to invert a `RasterizedPolygonOverlay` so that it rasterizes outside the polygon instead of inside. The `RasterizedPolygonsTileExcluder` also takes into account whether the polygon overlay is inverted. If so, tiles outside the polygons will be excluded instead of tiles within.
> Add option to invert polygon selections

- CHANGES.md
- Cesium3DTilesSelection/src/TilesetLoadTilesetDotJson.cpp
Some third-party terrain tiling tools generate an incorrect "bounds" property in layer.json, and these tilesets still work in CesiumJS because it ignores this property. This PR makes cesium-native match the CesiumJS behavior.
I could argue that CesiumJS is wrong and should change, but because quantized-mesh / layer.json is basically a legacy format at this point (and had a rather informal specification to begin with), compatibility is more important than correctness.
See https://community.cesium.com/t/cesium-terrain-for-unreal/17940/18.
> Ignore layer.json "bounds" property.

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterMappedTo3DTile.h
- Cesium3DTilesSelection/src/GltfContent.cpp
- Cesium3DTilesSelection/src/RasterMappedTo3DTile.cpp
- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/upsampleGltfForRasterOverlays.cpp
- Cesium3DTilesSelection/src/upsampleGltfForRasterOverlays.h
- Cesium3DTilesSelection/test/TestUpsampleGltfForRasterOverlay.cpp
Pull request in order to fix #385. 
This creates bounding volumes for the four upsampled tiles using the first raster overlay tile that has more detail.
It will also upsample using that same projection.
To make sure that it uses the same projection, it makes sure that the previous raster overlay tiles in the list do not have more data.
Update: During upsampling, its posssible that all the primitives are clipped out. In this case, it returns a std::nullopt.
> Upsample using first overlay with more detail

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TileContent.h
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.cpp
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.h
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.h
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.h
- Cesium3DTilesSelection/src/TileContent.cpp
- Cesium3DTilesSelection/src/TilesetContentLoader.h
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.h
This PR addresses the feedback for [the refactor PR comment](https://github.com/CesiumGS/cesium-native/pull/508#discussion_r889857003)
The PR adds `TilesetContentLoader::updateTileContent(Tile &tile)` to allow loader to update the tile content piece by piece if needed. The function allows the implicit tileset to create the children of tile if needed, instead of creating all children in the subtree. The function returns a boolean to indicate if the tile should be continue updated in the next frame. For the implicit tileset, once it creates the children for the tile, it will return false to indicate that the `updateTileContent()` should no longer be called on this tile in the future.
Along with this PR, I move `std::function<Tile &> tileInitializer` to `TileExternalContent`. The original …
> Allow tileset loader to update tile content

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/Tileset.cpp
- package-lock.json
- This PR contains adding a new API `computeLoadProgress` to the `Tileset` class.
- We added a counter keeping track of the current number of loaded tiles in the tileset to avoid counting the doubly linked list of loaded tiles every frame. 
- The load progress computation currently takes into account the three loading queues (`low`, `medium`, `high`), current `loadsInProgress`.
> Add API call for current tileset load progress

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetLoadTilesetDotJson.cpp
- This PR addresses #489 
- Removes `supportRasterOverlays` from `Tileset`. 
- @nithinp7
> Remove supportsRasterOverlays bool

- CesiumJsonReader/src/JsonObjectJsonHandler.cpp
Example tileset.json snippet that was failing:
```json
{
"asset": {
"version": "1.0"
},
"extensions": {
"3DTILES_metadata": {
"tileset": {
"properties": {
"propertyA": "stuff",
"propertyB": ["a", "b", "c"], // crashes here
"propertyC": [0, 1, 2, 3]
}
}
}
}
}
```
> Fix array of string parsing in JsonObjectJsonHandler

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/Tileset.cpp
- A follow up update for https://github.com/CesiumGS/cesium-unreal/issues/774 
- Update the API for getting the current loaded percentage from returning an unsigned int to a float.
> Change tileset load percentage to float

- CHANGES.md
- Cesium3DTilesSelection/src/RasterOverlayTileProvider.cpp
- Cesium3DTilesSelection/src/TileMapServiceRasterOverlay.cpp
Fixes #469 and #468.
Currently works with all the geoserver examples, gdal2tiles.py using mercator profile, but not gdal2tiles.py with geodetic profile
File 0/0/0.png of gdal2tiles.py: 
File 0/0/0.png of geoserver: 
the tileresource.xml document from geoserver:
```
<TileMap version="1.0.0" tilemapservice="http://localhost:8080/geoserver/gwc/service/tms/1.0.0">
<Title>BlueMarbleNG-TB_2004-12-01_rgb_3600x1800</Title>
<Abstract/>
<SRS>EPSG:4326</SRS>
<BoundingBox minx="-180.0" miny="-90.0" maxx="180.0" maxy="90.0"/>
<Origin x="-180.0" y="-90.0"/>
<TileFormat width="256" height="256" mime-type="image/png" extension="png"/>
<TileSets profile="local">
<TileSet href="http://localhost:8080/geoserver/gwc/service/tms/1.0.0/cite%3ABlueMarbleNG-TB_2004-12-01_rgb_3600x1800@EPSG%3A4326@png/0" …
```
> Tms update

- CHANGES.md
- CesiumAsync/src/SqliteCache.cpp
Because of an error in a SQL statement, the last access time in the request cache was not updated on cache hit. This could lead to the wrong requests being evicted from the cache.
> Update SqliteCache last access time correctly

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/GltfUtilities.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterMappedTo3DTile.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterOverlayCollection.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterOverlayDetails.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tile.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TileContent.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.cpp
- Cesium3DTilesSelection/src/GltfUtilities.cpp
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.h
- Cesium3DTilesSelection/src/RasterMappedTo3DTile.cpp
- Cesium3DTilesSelection/src/RasterOverlayCollection.cpp
- Cesium3DTilesSelection/src/RasterOverlayDetails.cpp
- Cesium3DTilesSelection/src/RasterOverlayUpsampler.cpp
- Cesium3DTilesSelection/src/RasterOverlayUpsampler.h
- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/TileContent.cpp
- Cesium3DTilesSelection/src/TileContentLoadInfo.cpp
- Cesium3DTilesSelection/src/TileContentLoadInfo.h
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetContentLoader.h
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.h
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
This PR adds back raster overlay code to the refactored loader:
- Since Tile no longer stores the tileset, `IPrepareRendererResources` is passed to `MappedRasterToTile` directly to create render resources for raster
- In the main branch, upsampling code is used to handle both quantized mesh and raster overlay. In this branch, if the loader produced upsampled tile ID, it will be responsible for upsampling that tile. So in this case, layerjson will handle upsampling its own tile, and there is a RasterOverlayUpsampler which will handle the upsampling for raster overlay tiles
- TilesetContentManager will check if a tile has an upsampled tile ID or not. If it's an upsampled tile, it will check if the parent is loaded before loading this tile. This condition is for any generic loaders where …
> Add raster overlay back to the refactor code

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/GltfUtilities.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TileContent.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/GltfUtilities.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.h
- Cesium3DTilesSelection/src/TileContent.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.h
This PR adds the credit code back to the refactored loader. It should handle:
- credit for Raster Overlay
- credit for Tileset and Quantized Mesh Layers
- credit for gltf
- credit for each raster overlay tiles
> Add credit back to the refactored code

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterOverlayCollection.h
- Cesium3DTilesSelection/src/RasterOverlayCollection.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
This PR is part of the refactor series #481. Raster Overlay collection now only uses `TilesetExternals` and `Tile::LoadedLinkList` to attach raster overlay to tile. This makes TilesetContentManager easier to test without involving Tileset since the manager depends on the raster overlay collection which requires tileset to be constructed in the previous implementation.
This is also the last dependency between the traversal (residing in tileset itself) and loading systems. By removing it, client can totally build their own traversal outside of Cesium Native and reuse the current loading system as they see fit
> Remove dependency between tileset and Raster Overlay Collection

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TileContent.h
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.cpp
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.h
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.h
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.h
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.h
- Cesium3DTilesSelection/src/RasterOverlayUpsampler.cpp
- Cesium3DTilesSelection/src/RasterOverlayUpsampler.h
- Cesium3DTilesSelection/src/TileContent.cpp
- Cesium3DTilesSelection/src/TilesetContentLoader.cpp
- Cesium3DTilesSelection/src/TilesetContentLoader.h
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.h
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.h
This is part of the refactor series #481. The loader now only accepts the const reference of tile in `TilesetContentLoader::loadTileContent()`. `TilesetContentLoader::updateTileContent()` is changed to `TilesetContentLoader::createTileChildren()` and accepts the const ref for tile as well
> Let loader interface to accept const reference of tile

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterOverlayCollection.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.h
- Cesium3DTilesSelection/test/TestTilesetContentManager.cpp
This PR is part of the refactor series #481. In the current refactor-branch, the content manager doesn't own the root tile and the raster overlay collection. The tileset itself owns those fields. However, it is quite awkward to manage the lifetime of those components:
- Because the manager only captures the pointer of `RasterOverlayCollection`, client of the manager (in this case, it's the `Tileset`) has to make sure the collection doesn't die; otherwise, we have a dangling pointer. But the `Tileset` itself doesn't use the collection in its implementation, so it doesn't make sense to let the tileset own it. Instead, the manager should own this collection, since it is the main client of the collection.
- The reason for moving the root tile to the manager is that the manager will create …
> Let content manager owns root tile and raster overlay collection

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TilesetContentLoader.h
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.cpp
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.h
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.h
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.h
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.h
- Cesium3DTilesSelection/src/RasterOverlayUpsampler.cpp
- Cesium3DTilesSelection/src/RasterOverlayUpsampler.h
- Cesium3DTilesSelection/src/TileContentLoadInfo.cpp
- Cesium3DTilesSelection/src/TileContentLoadInfo.h
- Cesium3DTilesSelection/src/TilesetContentLoader.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.h
- Cesium3DTilesSelection/test/TestTilesetContentManager.cpp
- Cesium3DTilesSelection/test/TestTilesetJsonLoader.cpp
This is part of the refactor series #481. This addresses the PR comment https://github.com/CesiumGS/cesium-native/pull/508#discussion_r947569181 by adding up axis to TileLoadResult structure.
This also creates helper methods `TileLoadResult::createFailedResult()` and `TileLoadResult::createRetryLaterResult()` to create results with Failed and RetryLater states
> Add up axis to TileLoadResult

- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.h
- Cesium3DTilesSelection/src/TilesetContentLoaderResult.h
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.h
- Cesium3DTilesSelection/test/TestTilesetContentManager.cpp
Previously when a url is passed to tileset, it will be able to load the layer.json format as well. This PR adds that support for the refactor
> Support layer.json when passing url

- Cesium3DTilesSelection/src/B3dmToGltfConverter.cpp
Maybe there's different approach? Initializing `headerLength` shouldn't be necessary in this case but it keeps gcc quiet.
```
cmake -B build -S . -D CMAKE_CXX_COMPILER=g++-11 -D CMAKE_C_COMPILER=gcc-11 && cmake --build build --parallel 8
/home/slilley/Code/cesium-native/Cesium3DTilesSelection/src/B3dmToGltfConverter.cpp: In static member function ‘static Cesium3DTilesSelection::GltfConverterResult Cesium3DTilesSelection::B3dmToGltfConverter::convert(const gsl::span<const std::byte>&, const CesiumGltfReader::GltfReaderOptions&)’:
/home/slilley/Code/cesium-native/Cesium3DTilesSelection/src/B3dmToGltfConverter.cpp:249:43: error: ‘headerLength’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
249 |   convertB3dmMetadataToGltfFeatureMetadata(
| …
```
> Fix gcc-11 build

- Cesium3DTilesSelection/src/TilesetContentManager.cpp
Fixes #555 
The reason is the tile is transitioned to a new state after per frame instead of transitioning to Done within a single frame. So the glTF render resources maybe created when transitioning fron ContentLoaded -> Done, but the raster overlay hasn't attached to it yet before the tile is rendered
> Update raster tile right after content has glTF render resources

- CHANGES.md
- CesiumGltfWriter/generated/src/ModelJsonWriter.cpp
- CesiumGltfWriter/test/TestGltfWriter.cpp
- tools/generate-classes/generate.js
In CesiumGltfWriter we had a special case where `byteOffset` would always get written out even if the value was 0. This causes problems when you have accessors that don't point to buffer views since it's invalid to have `byteOffset: 0` if no `bufferView` is defined. I noticed this when writing out glTFs with `KHR_draco_mesh_compression`.
> CesiumGltfWriter - remove special case for `byteOffset`

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TileContent.h
- Cesium3DTilesSelection/src/Tileset.cpp
Previously, fading in tiles went from 0.0 --> 1.0 and fading out tiles went from 1.0 --> 0.0. When these values are used to threshold a dither texture in a renderer, this small discrepancy might cause floating point disagreement between fading in tiles and fading out tiles. So instead, we now want fading in and fading out tiles to have the exact same dither threshold (fade percentage) and simply invert the resulting sample if it is fading out. Since the dither texture is sampled in screen-space, this allows the fading out tiles and fading in tiles to blend together perfectly without appearing transparent.
@kring came up with the idea and it works quite nicely!
> Flip the range for fade-out

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/IPrepareRendererResources.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TilesetOptions.h
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/test/SimplePrepareRendererResource.h
Closes #480. This PR adds a `rendererOptions` field to `TilesetOptions`, which gets passed to `IPrepareRendererResources::prepareInLoadThread` similar to how `RasterOverlayOptions` has its `rendererOptions` passed to `IPrepareRendererResources::prepareRasterInLoadThread`.
I couldn't find an equivalent unit test for `RasterOverlayOptions / RasteryOverlayTileProvider` -- would it be good to write one for this PR?
> Add `rendererOptions` to `TilesetOptions`

- CHANGES.md
- CesiumGeospatial/include/CesiumGeospatial/LocalHorizontalCoordinateSystem.h
- CesiumGeospatial/src/LocalHorizontalCoordinateSystem.cpp
- CesiumGeospatial/test/TestLocalHorizontalCoordinateSystem.cpp
This is kind of like the cesium-native side of cesium-unreal's CesiumGeoreference.
You give it a point on the globe and tell it which direction (west, south, east, north, up, down) each coordinate axis points, and it creates a coordinate system centered on the point and with the axes you specified. Depending on the directions you choose for the axes, the coordinate system may be right- or left-handed. You can also specify a `scale` parameter if the coordinate system is not in meters.
For example, it's easy to construct a left-handed, East-South-Up coordinate system in centimeters, like the one we use in Unreal Engine:
```
LocalHorizontalCoordinateSystem coordinateSystem(
Cartographic::fromDegrees(-105.25737, 39.736401, 2250.0),
LocalDirection::East,
LocalDirection::South, …
```
> Add LocalHorizontalCoordinateSystem

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterMappedTo3DTile.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterOverlayCollection.h
- Cesium3DTilesSelection/src/RasterMappedTo3DTile.cpp
- Cesium3DTilesSelection/src/RasterOverlayCollection.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
This fixes a bug, probably introduced in #554, that made it impossible to add raster overlays to some tilesets, such as Melbourne Photogrammetry.
When a tile turns out to not have the projection necessary for a particular raster overlay, we have no way to determine the tile's rectangle for overlay mapping purposes. So we attach a placeholder raster overlay tile to it and then kick the tile back to the unloaded state to start over. Except we weren't creating the placeholder tile properly, and instead ended up creating a RasterMappedTo3DTile that had both its loading and ready tiles null. So it would get stuck there not ready forever.
This PR fixes the problem by creating the placeholder tile correctly, which requires access to the placeholder tile provider. I also considered making a …
> Create placeholder tile properly when rectangle is unknown.

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/GltfUtilities.h
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- CesiumGeospatial/include/CesiumGeospatial/BoundingRegionBuilder.h
- CesiumGeospatial/src/BoundingRegionBuilder.cpp
This fixes a problem reported on the community forum:
https://community.cesium.com/t/unreal-crash-when-i-add-a-cesiumtmsrasteroverlay-to-a-cesium3dtileset/20996
The tileset from the forum consisted of buildings, and was (as is typical of buildings) relatively sparse. Some areas had buildings, some areas had holes where there were no buildings. So if we zoomed in close, we might need to upsample for the raster overlays, and some of the upsampled children might not contain any geometry at all. The computed bounding volume for such a tile would by empty: west would be greater than east, south greater than north, and minimum height greater than maximum. However, the min/max heights would be roughly +/- 1e308. When we later tried to create a BoundingRegion like this, we'd end up with an …
> Don't try to upsample tiles with no geometry.

- CHANGES.md
- Cesium3DTilesSelection/src/TileMapServiceRasterOverlay.cpp
- Cesium3DTilesSelection/src/WebMapServiceRasterOverlay.cpp
`TileMapServiceRasterOverlay` and `WebMapServiceRasterOverlay` (unlike all the other raster overlay types) were both creating their tile provider in a `thenInWorkerThread` continuation, capturing an intrusive pointer to the `RasterOverlay` in order to do this. This can trigger an assertion failure in `ReferenceCountedNonThreadSafe` when it detects an attempt to decrement the reference count from the wrong thread, and could also (rarely) cause the reference count itself to get corrupted.
The fix in this PR is to do this small amount of work in the main thread instead. If response parsing for these raster overlay types ever turns out to be a main thread bottleneck, we can refactor it into a `thenInWorkerThread` continuation that does the parsing followed by a `thenInMainThread` that creates …
> Create TMS and WMS tile providers in the main thread.

- CesiumUtility/include/CesiumUtility/ReferenceCountedNonThreadSafe.h
there missed macro condition.
now I hava building successfully  with windows 11 by visual studio 2019.
> fix building error when enable tracing

- Cesium3DTilesSelection/src/WebMapServiceRasterOverlay.cpp
It's safer and Xcode 14 reports a warning on use of sprintf which turns into an error, breaking the build.
> Use snprintf instead of sprintf.

- Cesium3DTiles/generated/include/Cesium3DTiles/ImplicitTiling.h
- Cesium3DTiles/generated/include/Cesium3DTiles/PropertyTableProperty.h
- Cesium3DTiles/generated/include/Cesium3DTiles/Tile.h
- CesiumGltf/generated/include/CesiumGltf/AccessorSpec.h
- CesiumGltf/generated/include/CesiumGltf/AnimationChannelTarget.h
- CesiumGltf/generated/include/CesiumGltf/AnimationSampler.h
- CesiumGltf/generated/include/CesiumGltf/Camera.h
- CesiumGltf/generated/include/CesiumGltf/ExtensionBufferViewExtMeshoptCompression.h
- CesiumGltf/generated/include/CesiumGltf/ExtensionExtStructuralMetadataPropertyTableProperty.h
- CesiumGltf/generated/include/CesiumGltf/FeatureTableProperty.h
- CesiumGltf/generated/include/CesiumGltf/Material.h
- tools/generate-classes/resolveProperty.js
The generated glTF and 3D Tiles classes would previously use `std::string` for enums without first adding `#include <string>`. So this would fail to compile if someone else hadn't coincidentally included the string header prior.
> Include string header for string enums.

- CHANGES.md
- Cesium3DTilesSelection/src/Tileset.cpp
Fixes #585 
Before:
After:
I saw some more obvious examples yesterday, but can't find them now. In some cases the bug might prevent buildings from showing up at all, no matter how much you zoom in, which makes it harder to spot that you've been impacted by the bug.
> Don't cull with children bounds for additive-refined tilesets.

- CesiumAsync/test/TestInternalTimegm.cpp
- extern/CMakeLists.txt
The version we were previously using (untagged, roughly v8.0.0) cannot be build for x86_64 Android (Magic Leap 2). This PR upgrades to the current head of the master branch, because no tagged version supports this architecture yet.
But the CMake scripts at the head commit (and also the last tagged release, v9.0.0) don't work with multi-config generators (Visual Studio). tinyxml2 is one .cpp file and one .h, so I just added a two line manual build for it instead.
> Upgrade tinyxml2

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/ITileExcluder.h
- Cesium3DTilesSelection/src/Tileset.cpp
This gives a tile excluder an opportunity to do once-per-frame updates, such as computing a new transformation if a tileset moved.
> Add ITileExcluder::startNewFrame

- Cesium3DTilesSelection/src/RasterOverlayCollection.cpp
- Cesium3DTilesSelection/src/RasterOverlayTileProvider.cpp
- CesiumUtility/include/CesiumUtility/Tracing.h
- CesiumUtility/src/Tracing.cpp
cesium-native didn't compile with tracing enabled (see #267 for details of how to set that up), so this PR fixes that.
It also disables the use of tracks for raster overlay loading. The idea behind a "track" is to visualize each of our loading slots as a virtual thread, so we can see the breakdown of the entire loading process even as it progresses across multiple threads. But we lost the ability to do this for tileset content loading in #548. And for raster overlays, we still had it in theory, but it didn't work right after #325 because multiple overlay tiles could end up loaded in parallel in a single track when multiple tiles from the raster overlay service overlapped a single terrain/geometry tile.
Rather than fixing all that, this PR just removes the use of tracks entirely. So at …
> Fix compile error when tracing is enabled, disable trace tracks for raster overlays

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/CreditSystem.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/CreditSystem.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/test/TestCreditSystem.cpp
This is a small change that allows a credit's `showOnScreen` value to be overridden whenever it is retrieved. This allows a tileset's `showCreditsOnScreen` option to immediately take place.
> Add ability to override `showOnScreen` in credit

- Cesium3DTilesSelection/src/WebMapServiceRasterOverlay.cpp
Hello.
I found that some wms service needs key in url.
for example.
https://api.wms.example.com/req/wms?KEY={MY-PRIVATE-KEY}&DOMAIN={MY-OWN-DOMAIN}
This changes is for if wms url already has query string(?) in url string, then replace with & instead of ? in following parameter string.
please review this PR.
Thanks!
> Handling when query string is included in WMS url

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/Tileset.cpp
This fixes a bug that causes holes to sometimes appear when flying around the San Francisco tileset, even with "Forbid Holes" enabled.
Unfortunately, I don't know exactly why it happens. The immediate cause is that the selection algorithm is choosing to "render" an external tileset Tile, which is not actually renderable because it has no content. It does this because it can't render the tileset's children, because they're not loaded yet. This situation is supposed to be prevented by the "Forbid Holes" mode's requirement that all sibling tiles - even culled ones - be loaded before any of them can be rendered. This should be further enforced by the "kick" mechanism, which should "un-select" a subtree that doesn't meet this requirement. But in this case, the kicking doesn't (and can't) …
> Fix a bug causing holes in some tilesets, like San Francisco.

- Cesium3DTilesSelection/src/B3dmToGltfConverter.cpp
- Cesium3DTilesSelection/src/BatchTableToGltfFeatureMetadata.cpp
- Cesium3DTilesSelection/src/BatchTableToGltfStructuralMetadata.cpp
- Cesium3DTilesSelection/src/BatchTableToGltfStructuralMetadata.h
- Cesium3DTilesSelection/src/PntsToGltfConverter.cpp
- Cesium3DTilesSelection/test/TestPntsToGltfConverter.cpp
- Cesium3DTilesSelection/test/TestUpgradeBatchTableToExtFeatureMetadata.cpp
I'm going to use `upgrade-feature-metadata` as a staging branch for the metadata extension changes, since it's going to involve a larger overhaul and I want to make changes as incrementally as possible.
In this PR, batch IDs are stored `EXT_mesh_features` instead of an `EXT_feature_metadata` extension on the mesh primitive. This change only affects `b3dm` / `pnts`; a separate class should be written to convert `EXT_feature_metadata` to `EXT_mesh_features` for glTFs.
I also prematurely renamed the file before deciding to split up PRs. In this PR it doesn't handle `EXT_structural_metadata` yet.
> Use `EXT_mesh_features` to indicate batch IDs

- CesiumGltf/include/CesiumGltf/StructuralMetadataPropertyView.h
- CesiumGltf/include/CesiumGltf/getOffsetFromOffsetsBuffer.h
- CesiumGltf/test/TestStructuralMetadataPropertyView.cpp
This PR creates a `StructuralMetadata` counterpart to `MetadataPropertyView`. This handles `vecN` and `matN` properties in addition to the existing ones. There are slight rewrites of the documentation and internal code for clarity.
> Add `StructuralMetadataPropertyView`

- CesiumGltf/include/CesiumGltf/StructuralMetadataArrayView.h
- CesiumGltf/include/CesiumGltf/StructuralMetadataPropertyTableView.h
- CesiumGltf/include/CesiumGltf/StructuralMetadataPropertyType.h
- CesiumGltf/include/CesiumGltf/StructuralMetadataPropertyView.h
- CesiumGltf/src/StructuralMetadataPropertyTableView.cpp
- CesiumGltf/src/StructuralMetadataPropertyType.cpp
- CesiumGltf/test/TestStructuralMetadataPropertyTableView.cpp
- CesiumGltf/test/TestStructuralMetadataPropertyView.cpp
This PR adds `MetadataPropertyTableView`, the `EXT_structural_metadata` version of `MetadataFeatureTableView`. This is used to retrieve properties via a `MetadataPropertyView`. With this, all of the internal overhaul should be done, and we can actually convert the extensions themselves.
> Add `MetadataPropertyTableView`

- Cesium3DTilesSelection/src/B3dmToGltfConverter.cpp
- Cesium3DTilesSelection/src/BatchTableToGltfStructuralMetadata.cpp
- Cesium3DTilesSelection/src/PntsToGltfConverter.cpp
- Cesium3DTilesSelection/test/TestPntsToGltfConverter.cpp
- Cesium3DTilesSelection/test/TestUpgradeBatchTableToExtStructuralMetadata.cpp
- CesiumGltf/include/CesiumGltf/StructuralMetadataPropertyTableView.h
- CesiumGltf/src/StructuralMetadataPropertyTableView.cpp
This PR rewrites how batch tables in `b3dm` and `pnts` formats are parsed. They are now stored as a property table in a glTF with the `EXT_mesh_features` and `EXT_structural_metadata` extensions. The tests have also been rewritten to accommodate this difference.
> Convert batch tables to `EXT_structural_metadata`

- Cesium3DTilesSelection/src/B3dmToGltfConverter.cpp
- Cesium3DTilesSelection/src/BatchTableToGltfStructuralMetadata.cpp
- Cesium3DTilesSelection/src/PntsToGltfConverter.cpp
- Cesium3DTilesSelection/test/TestPntsToGltfConverter.cpp
- Cesium3DTilesSelection/test/TestUpgradeBatchTableToExtStructuralMetadata.cpp
- CesiumGltf/include/CesiumGltf/StructuralMetadataPropertyTablePropertyView.h
- CesiumGltf/include/CesiumGltf/StructuralMetadataPropertyTableView.h
- CesiumGltf/include/CesiumGltf/StructuralMetadataPropertyTexturePropertyView.h
- CesiumGltf/include/CesiumGltf/StructuralMetadataPropertyTextureView.h
- CesiumGltf/src/StructuralMetadataPropertyTableView.cpp
- CesiumGltf/src/StructuralMetadataPropertyTexturePropertyView.cpp
- CesiumGltf/src/StructuralMetadataPropertyTextureView.cpp
- CesiumGltf/test/TestStructuralMetadataPropertyTablePropertyView.cpp
- CesiumGltf/test/TestStructuralMetadataPropertyTableView.cpp
- CesiumGltf/test/TestStructuralMetadataPropertyTexturePropertyView.cpp
- CesiumGltf/test/TestStructuralMetadataPropertyTextureView.cpp
This adds `EXT_structural_metadata` counterparts of `FeatureTextureView` and `FeatureTexturePropertyView`. It also renames the `PropertyTableView` and `PropertyTablePropertyView` classes, and their error enums, to be consistent with the property texture naming scheme.
I kept most of the implementation of `FeatureTextureView` and `FeatureTexturePropertyView` because I'm not familiar with how it interfaces with Unreal, and I don't want to make potentially incompatible changes. But I'm not happy with the inconsistencies between property table / property texture implementations. For instance,
- `PropertyTableView` doesn't validate all of its properties on construction, but `PropertyTextureView` does.
- `PropertyTextureView` is marked invalid if one of its properties is invalid, but …
> Add views for property textures and their properties

- Cesium3DTilesSelection/src/upsampleGltfForRasterOverlays.cpp
The old code duplicated the metadata in `EXT_feature_metadata`; we want to do that for `EXT_structural_metadata` now.
> Use `EXT_structural_metadata` in `upsampleGltfForRasterOverlays`

- doc/CMakeLists.txt
fixes #672. @kring pointed out that these missing headers just need to be added to the documentation `CMakeLists.txt`. Looking for other generated headers I found the following dirs:
```sh
Cesium3DTiles/generated/include
Cesium3DTilesReader/generated/src
Cesium3DTilesWriter/generated/src
CesiumGltf/generated/include
CesiumGltfReader/generated/src
CesiumGltfWriter/generated/src
```
Looking through the `src` dirs I didn't see anything with doxygen-style comments so I only added the two with `include` subdirs.
> include generated headers in doxygen documentation

- Cesium3DTilesSelection/test/TestQuadtreeRasterOverlayTileProvider.cpp
Trying to fool around with cesium using the new C++ intrerop with swift and ran into the following errors building with cmake on macOS. 
[ 86%] Built target csprng
[ 88%] Built target CesiumIonClient
[ 88%] Building CXX object CesiumNativeTests/CMakeFiles/cesium-native-tests.dir/__/Cesium3DTilesSelection/test/TestQuadtreeRasterOverlayTileProvider.cpp.o
/Users/jacobmartin/Documents/Development/cesium-native/Cesium3DTilesSelection/test/TestQuadtreeRasterOverlayTileProvider.cpp:162:14: error: variable 'i' set but not used [-Werror,-Wunused-but-set-variable]
for (int i = 0; pTile->getState() != RasterOverlayTile::LoadState::Loaded;
^
/Users/jacobmartin/Documents/Development/cesium-native/Cesium3DTilesSelection/test/TestQuadtreeRasterOverlayTileProvider.cpp:217:14: error: variable 'i' set but …
> Fix in response to unused but set var

- CesiumUtility/CMakeLists.txt
- extern/CMakeLists.txt
On configure, zlib renames `zconf.h` to `zconf.h.included` for no good reason, causing git to report its repo as dirty. The dirty repo then propagates up through cesium-native into whatever projects are using it via submodule, which is really annoying. There are a [bunch of issues](https://github.com/madler/zlib/issues?q=is%3Aissue+is%3Aopen+zconf.h.included) written for this, along with multiple PRs to fix it in different ways, but seemingly no interest from the maintainers.
So the hacky approach I used here is to simply rename it back after the zlib `add_subdirectory`. Since the rename was pointless to begin with, this doesn't do any harm and avoids a dirty repo.
> Don't let zlib dirty its repo on configure

- Cesium3DTilesSelection/src/GltfConverters.cpp
These logs appear to be informational in nature and are visible in the console when using Cesium for Unity. I've also noticed these in the unit tests output for Cesium for Unreal.
Ultimately, I decided to remove these completely. In the context our official releases, I didn't see much use. Our supported magic headers and file extensions are not configurable by a user. So really it's just verifying the call to `Cesium3DTilesSelection::registerAllTileContentTypes()`, which is informative, but isn't particularly complicated. For example, in the Cesium for Unreal plugin, this call only happens once, and always during plugin startup.
Fixes #679
> Remove logs when registering magic headers of file extensions

- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.h
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/test/TestLayerJsonTerrainLoader.cpp
The `showCreditsOnScreen` argument was passed all the way down through the call chains in `LayerJsonTerrainLoader`, and apparently, it was not used.
Opening this as a DRAFT, because I don't know whether...
- the fact that it was passed on was unintentional
- the fact that it was not used was unintentional
- (Maybe I overlooked some place where it was used, but if this is the case, then there was no test that took this flag into account - all tests still seem to be passing...)
Maybe someone wants to have a look...
> Remove credits argument

- CMakeLists.txt
This is needed to make the meshoptimizer lib available to cesium-unreal.
> Install meshoptimizer targets.

- CHANGES.md
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
There was a small regression in https://github.com/CesiumGS/cesium-native/pull/646 where an invalid error would get propagated to the tileset's `loadErrorCallback`. Fixed by wrapping in a `if (result.errors)` check.
Feel to free to tweak for style as needed (e.g. maybe the if statements should be combined into one?).
> Prevent empty error message from getting propagated to loadErrorCallback

- CHANGES.md
- CesiumGltf/src/Ktx2TranscodeTargets.cpp
- CesiumGltfReader/src/GltfReader.cpp
When KTX transcoding fails, the image will now be fully decompressed instead of returning an error.
> Fully decompress KTX images if transcoding fails.

- CHANGES.md
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.h
- Cesium3DTilesSelection/test/TestTilesetContentManager.cpp
This fixes the Unreal Movie Render Queue freezing that several users have noticed in Cesium for Unreal v1.29.0:
https://community.cesium.com/t/movie-render-queue-freeze-at-lower-values-for-maximum-screen-space-error/26331
Here's what's happening:
1. A tile needs to be upsampled in order to hang more detailed raster overlays on it.
2. That tile can't be upsampled until its parent enters the Done state, because we need the parent geometry in order to do the upsampling.
3. `TilesetContentManager::loadTileContent` detects this case, and explicitly calls `loadTileContent` on the parent tile. Because there's no guarantee the parent tile would ever load otherwise.
4. `loadTileContent` allows the parent tile to complete its request and worker thread work, but by itself it will only get the tile …
> Finish loading parent tile when needed for upsampling.

- CHANGES.md
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
Fixes crash reported here:
https://community.cesium.com/t/latest-update-crash/26513
In #721, I added a call to `finishLoading` in a case that it was needed. `finishLoading` switches the tile into the `Done` state, which should guarantee that `finishLoading` won't get called again later. Or so I thought. The problem is that the tile may have been added to the main thread load queue while it was in the `ContentLoaded` state, but then by the time the main thread load queue is processed, by new call to finishLoading has already happened and so the tile is in the Done state. This would cause an assertion failure in debug builds, but in release builds it tends to just crash because the game engine integration interprets the renderer resources incorrectly.
The solution in this PR is to …
> Fix crash caused by redundant finishLoading call.

- CesiumGltf/include/CesiumGltf/FeatureTexturePropertyView.h
Needed by `std::clamp`. This showed up in the Unreal Engine 5.3 build.
> Add missing include.

- CHANGES.md
- CesiumGltf/include/CesiumGltf/PropertyAttributePropertyView.h
- CesiumGltf/include/CesiumGltf/PropertyAttributeView.h
- CesiumGltf/include/CesiumGltf/PropertyTablePropertyView.h
- CesiumGltf/include/CesiumGltf/PropertyTableView.h
- CesiumGltf/include/CesiumGltf/PropertyTexturePropertyView.h
- CesiumGltf/include/CesiumGltf/PropertyTextureView.h
- CesiumGltf/include/CesiumGltf/PropertyView.h
- CesiumGltf/src/PropertyTableView.cpp
- CesiumGltf/src/PropertyView.cpp
- CesiumGltf/test/TestPropertyAttributeView.cpp
- CesiumGltf/test/TestPropertyTableView.cpp
- CesiumGltf/test/TestPropertyTexturePropertyView.cpp
- CesiumGltf/test/TestPropertyTextureView.cpp
This PR adds support for properties that are omitted from a property table / texture / attribute instance. This is allowed by the spec so long as the `ClassProperty` is not `required`. A special case happens if an omitted `ClassProperty` defines a default value; ideally, this value should be used by for metadata picking / styling in our runtime engines. However, in the current implementation it creates `ErrorNonexistentProperty` instances for these omitted properties. Technically, this is not wrong, but it may be confusing when trying to convey what data is actually available to users. 
My initial approach was to restrict the `forEachProperty` functions in `PropertyTable`, `PropertyTexture` and `PropertyAttribute`. They would only handle properties that were actually defined in the …
> Support omitted `EXT_structural_metadata` properties

- CesiumGltf/include/CesiumGltf/PropertyAttributePropertyView.h
- CesiumGltf/include/CesiumGltf/PropertyTablePropertyView.h
- CesiumGltf/include/CesiumGltf/PropertyTexturePropertyView.h
Followup to #726. This addresses @kring 's suggestion for improving the `EmptyPropertyWithDefault` constructor. Now when the constructor is called and `classProperty.defaultProperty` is not defined, the property view status is set to `ErrorNonexistentProperty`.
> Fix `EmptyPropertyWithDefault` constructors

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/ViewUpdateResult.h
- Cesium3DTilesSelection/src/Tileset.cpp
Addresses cases where `::ComputeLoadProgress` would report 100% done prematurely, before all work in the view had completed. 
(I noticed this in cesium-unreal performance tests, with Google 3D Tiles)
With certain tilesets and our "kicking' logic (`::_kickDescendantsAndRenderTile`), we can run into frames where all work has been kicked out of the main / worker threads, but no new work has been added yet. This could lead to a 100% value being returned, in error.
The fix is to consider frames that kicked tiles as not complete yet. This gives us at least one more view traversal to find remaining work.
> Tweak compute load progress

- CHANGES.md
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.cpp
This is a PR into the v0.27.x branch so that we can ship it in the next Cesium for Unreal v1.x release. v0.28 and main have the new metadata architecture that are targeted for v2.0.
> Add support for Cesium ion "externalType" assets.

- .gitignore
- CesiumIonClient/include/CesiumIonClient/Connection.h
I noticed that the authorization URL used in cesium-native is an old one that's doing a redirect last week. I checked with @mramato and confirmed that we should be using `https://ion.cesium.com/oauth`. This is just a PR to make this update.
P.S. I also added `.idea` to the `.gitignore` to prevent git from trying to scoop up the Clion prefs on my machine.
> Updated ion authorization url to the current url

- CMakeLists.txt
- extern/CMakeLists.txt
In cesium-unreal, the uriparser header files were being installed to `Source/ThirdParty/include` instead of `Source/ThirdParty/include/uriparser`. This PR fixes that.
> Install uriparser includes to the right location.

- CHANGES.md
- CesiumGltf/src/Accessor.cpp
Fixed loading failure issue when byteStride  description is 0 in buffer view
> Fix logical errors in byteStride calculations

- CHANGES.md
- CesiumGltf/include/CesiumGltf/PropertyAttributeView.h
Fixes `PropertyAttributeView::forEachProperty`. The parameter order just needed to be swapped.
> Fix `PropertyAttributeView::forEachProperty`

- CesiumGltf/include/CesiumGltf/PropertyAttributePropertyView.h
- CesiumGltf/include/CesiumGltf/PropertyAttributeView.h
- CesiumGltf/include/CesiumGltf/PropertyTableView.h
- CesiumGltf/include/CesiumGltf/PropertyTextureView.h
- CesiumGltf/include/CesiumGltf/PropertyView.h
- CesiumGltf/src/PropertyAttributeView.cpp
- CesiumGltf/src/PropertyTableView.cpp
- CesiumGltf/src/PropertyTextureView.cpp
- CesiumGltf/test/TestPropertyAttributeView.cpp
- CesiumGltf/test/TestPropertyTableView.cpp
- CesiumGltf/test/TestPropertyTextureView.cpp
The main thing here is renaming `propertyName` to `propertyId` for `getClassProperty`, `getPropertyView`, and related functions. This is to disambiguate the property id (the dictionary key) from the property name (its `name` field). When calling these functions you want to pass in the property id.
I also fixed some other doc issues that I noticed along the way.
> Fix property related docs

- CHANGES.md
- Cesium3DTilesContent/CMakeLists.txt
- Cesium3DTilesContent/include/Cesium3DTilesContent/TileBoundingVolumes.h
- Cesium3DTilesContent/include/Cesium3DTilesContent/TileTransform.h
- Cesium3DTilesContent/src/TileBoundingVolumes.cpp
- Cesium3DTilesContent/src/TileTransform.cpp
- Cesium3DTilesContent/test/TestTileBoundingVolumes.cpp
- Cesium3DTilesSelection/src/BoundingVolume.cpp
- CesiumGeometry/include/CesiumGeometry/BoundingSphere.h
- CesiumGeometry/include/CesiumGeometry/OrientedBoundingBox.h
- CesiumGeometry/src/BoundingSphere.cpp
- CesiumGeometry/src/OrientedBoundingBox.cpp
- CesiumGeometry/test/TestBoundingSphere.cpp
- CesiumGeometry/test/TestOrientedBoundingBox.cpp
This is a PR into #747 so merge that first.
Fixes #647 
- Added `TileBoundingVolumes` class to `Cesium3DTilesContent`, making it easier to create the rich bounding volume types in `CesiumGeometry` and `CesiumGeospatial` from the simple `std::vector` representations in `Cesium3DTiles`
- Added `transform` method to `CesiumGeometry::BoundingSphere`.
- Added `toSphere`, `fromSphere`, and `fromAxisAligned` methods to `CesiumGeometry::OrientedBoundingBox`.
- Added `TileTransform` class to `Cesium3DTilesContent`, making it easier to create a `glm::dmat4` from the `transform` property of a `Cesium3DTiles::Tile`.
> 3D Tiles bounding volume improvements

- CHANGES.md
- extern/CMakeLists.txt
Longer term, we should upgrade fmt. Our copy is included in spdlog.
https://github.com/fmtlib/fmt/issues/3540
> Fix VS 2022 17.8 warnings/errors by defining _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING

- CHANGES.md
- CesiumAsync/include/CesiumAsync/Future.h
- CesiumAsync/include/CesiumAsync/SharedFuture.h
- CesiumAsync/test/TestAsyncSystem.cpp
When using cesium-native's AsyncSystem, it often happens that you have some values computed inside one continuation that you want to pass to the next continuation in the chain. You can do this by bundling them up in a struct and returning that struct from the current continuation. Or even use a `std::tuple`, if defining a struct seems like too much ceremony. 
Unfortunately, that breaks down when the continuation itself returns another future. For example:
```cpp
whatever.thenInMainThread([](Whatever&& whatever) {
SomeType value = computeSomeValue(whatever);
return startAnAsyncOperation(value);
}).thenInMainThread([](AsyncOperationResult&& result) {
// ... do something with the result of the async operation
});
```
What if the "do something with the result of the async operation" also …
> Add thenPassThrough method to Future and SharedFuture

- CHANGES.md
- Cesium3DTiles/generated/include/Cesium3DTiles/BufferSpec.h
- Cesium3DTiles/generated/include/Cesium3DTiles/Properties.h
- Cesium3DTiles/generated/include/Cesium3DTiles/Tile.h
- Cesium3DTiles/include/Cesium3DTiles/Buffer.h
- Cesium3DTiles/include/Cesium3DTiles/BufferCesium.h
- Cesium3DTilesContent/CMakeLists.txt
- Cesium3DTilesContent/include/Cesium3DTilesContent/SubtreeAvailability.h
- Cesium3DTilesContent/src/SubtreeAvailability.cpp
- Cesium3DTilesContent/test/TestSubtreeAvailability.cpp
- Cesium3DTilesReader/CMakeLists.txt
- Cesium3DTilesReader/include/Cesium3DTilesReader/SubtreeFileReader.h
- Cesium3DTilesReader/src/SubtreeFileReader.cpp
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/test/TestImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/test/TestImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/test/data/ImplicitTileset/subtrees/0.0.0.json
- tools/generate-classes/3dTiles.json
This is a PR into #752 so merge that first.
This PR makes "querying" of implicit tile availability usable from outside the Cesium3DTilesSelection library and the selection-specific "loader" classes. It also adds the ability to modify availability information that is already loaded.
> Improve support for reading implicit tiling subtrees, and manipulating them after they're loaded

- CHANGES.md
- CesiumGltf/include/CesiumGltf/AccessorUtility.h
- CesiumGltf/src/AccessorUtility.cpp
- CesiumGltf/test/TestAccessorUtility.cpp
This PR adds `AccessorUtility.h`, which is just the `GltfAccessors.h` file from Cesium for Unreal. It provides `typedef`s for the possible types of feature ID, index, and texcoord accessors, as well as visitors to retrieve their data. This is useful for retrieving feature IDs and texture coordinates without requiring them to be baked into mesh data, enabling picking.
This is a PR into #756 , so merge that first.
> Add `AccessorUtility.h`

- CHANGES.md
- extern/CMakeLists.txt
This is the same as #767 except it's a PR into the v0.27.x branch, which we're still using in Cesium for Unity until we can update to the new metadata system.
> Fix VS 2022 17.8 warnings/errors in v0.27.x by defining _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING

- CHANGES.md
- Cesium3DTilesContent/src/SubtreeAvailability.cpp
- Cesium3DTilesContent/test/TestSubtreeAvailability.cpp
- Cesium3DTilesReader/include/Cesium3DTilesReader/SubtreeFileReader.h
- CesiumNativeTests/include/CesiumNativeTests/ThreadTaskProcessor.h
This change keeps SubtreeFileReader instance in the loaders future context. Should fix https://github.com/CesiumGS/cesium-native/issues/774
> Fix crash from accessing deleted SubtreeFileReader

- CHANGES.md
- CesiumIonClient/CMakeLists.txt
- CesiumIonClient/include/CesiumIonClient/Connection.h
- CesiumIonClient/include/CesiumIonClient/Defaults.h
- CesiumIonClient/src/Connection.cpp
- CesiumIonClient/src/Response.cpp
- CesiumIonClient/test/TestConnection.cpp
- CesiumIonClient/test/data/defaults.json
This is a PR into #772 so merge that first.
Adds support for Cesium ion's new `defaults` service which will be used to populate the Quick Add panels. The new service is not available in the public Cesium ion just yet, though.
> Add support for new defaults service to CesiumIonClient.

- CHANGES.md
- CesiumGltf/include/CesiumGltf/AccessorUtility.h
- CesiumGltf/test/TestAccessorUtility.cpp
I noticed while working in Unity that `IndicesForFaceFromAccessor`  made assumptions about the geometry -- it always assumed the mode was `TRIANGLES`. However, the math is completely different for `TRIANGLE_FAN` and `TRIANGLE_STRIP` modes.
I'm opening this PR to add proper support for the other triangle types.
> Add support for other primitive modes in `IndicesForFaceFromAccessor`

- CHANGES.md
- Cesium3DTilesContent/src/BatchTableToGltfStructuralMetadata.cpp
- Cesium3DTilesContent/test/TestUpgradeBatchTableToExtStructuralMetadata.cpp
- CesiumGltf/test/TestAccessorUtility.cpp
This PR fixes how batch tables choose `noData` values when upgrading to `EXT_structural_metadata`. Specifically,
- For signed `int`s, the order of checks in `getSentinelValue` prevented -1 from being chosen as a sentinel value if 0 was taken. The order has been changed to account for this.
- Unsigned `int`s will be upgraded to the next biggest signed `int` (if possible) if 0 cannot act as a sentinel value. This allows -1 to be used as its sentinel value instead.
- If no sentinel value is available for a property that has `null`, explicitly force it to a string property.
Without these checks, there is some unpredictable behavior because some of the code assumes a valid sentinel value exists, leading to dereferenced `nullopt`s 😬
> Fix how batch tables choose sentinel values

- CHANGES.md
- Cesium3DTilesContent/src/BatchTableToGltfStructuralMetadata.cpp
- CesiumGltf/include/CesiumGltf/PropertyTablePropertyView.h
- CesiumGltf/test/TestPropertyTablePropertyView.cpp
- CesiumGltf/test/TestPropertyTableView.cpp
Depends on #794, so merge that first.
In `EXT_structural_metadata`, the `arrayOffsets` of a `PropertyTableProperty` represent array indices. However, Cesium Native treats them as byte offsets that are multiples of `sizeof(T)`, which is wrong. This PR corrects this behavior and edits the unit tests for the proper values.
Also, I arbitrarily found and replaced instances of `glm::i32mat2x2 -> glm::imat2x2`, so the diff looks bigger than it actually needs to be 😅
> Interpret offsets as array indices, not byte offsets

- CesiumGltfReader/generated/src/registerExtensions.cpp
- CesiumGltfWriter/generated/src/registerExtensions.cpp
- package-lock.json
- tools/generate-classes/glTF.json
These two texture types have custom classes, `MaterialOcclusionTextureInfo` and `MaterialNormalTextureInfo`, but the `KHR_texture_transform` extension was configured to only apply to `TextureInfo` classes. The custom classes are derived from `TextureInfo`, but the code generator isn't that clever.
The end result was that instances of `KHR_texture_transform` attached to an occlusion or normal texture showed up as an unknown extension (expressed as a `JsonValue`) rather than as `ExtensionKhrTextureTransform`.
> Support texture transform extension on occlusion and normal textures.

- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- CesiumGltf/include/CesiumGltf/ImageCesium.h
- CesiumRasterOverlays/src/RasterOverlayTileProvider.cpp
Added a `sizeBytes` property to `ImageCesium`, so that its size can be tracked even after `pixelData` has been cleared (such as in CesiumGS/cesium-unreal#1330.
This is a little hacky. Arguably this information should be stored somewhere else, such as is in the `Tile` and/or `RasterOverlayTile`. But putting it here keeps things simpler, particularly around thread safety. In CesiumGS/cesium-unreal#1330, the pixel data is cleared in the worker thread. But worker threads, by design, don't have access to `Tile` or `RasterOveralyTile`. So it all gets very elaborate, and hard to justify.
> Track image data size independently of the `pixelData` array size

- CHANGES.md
- CesiumGeospatial/src/SimplePlanarEllipsoidCurve.cpp
- CesiumGeospatial/test/TestSimplePlanarEllipsoidCurve.cpp
The `SimplePlanarEllipsoidCurve` used for flight paths currently doesn't work for paths where the source point is below the surface of the ellipsoid. It currently causes the calculated coordinates to be inverted, giving points on the other side of the earth. This is because the math in `SimplePlanarEllipsoidCurve` first scales the source and destination points to the surface of the ellipsoid, and then assumes that these surface points must be lower in elevation than the original points for the rest of the calculations. This meant that height wasn't calculated correctly, and crucially, `_sourceDirection` was calculated pointing the wrong direction, resulting in the inverted coordinates. I've fixed the math so that it should work the same when points are below the ellipsoid.
> Fix `SimplePlanarEllipsoidCurve` when one of the points has a negative height

- CHANGES.md
- Cesium3DTilesContent/include/Cesium3DTilesContent/ImplicitTilingUtilities.h
- Cesium3DTilesContent/include/Cesium3DTilesContent/TileBoundingVolumes.h
- Cesium3DTilesContent/src/ImplicitTilingUtilities.cpp
- Cesium3DTilesContent/src/TileBoundingVolumes.cpp
- Cesium3DTilesContent/test/TestImplicitTilingUtilities.cpp
- Cesium3DTilesContent/test/TestTileBoundingVolumes.cpp
From the changelog:
- Added overloads of `ImplicitTilingUtilities::computeBoundingVolume` taking a `Cesium3DTiles::BoundingVolume`.
- Added overloads of `ImplicitTilingUtilities::computeBoundingVolume` taking an `S2CellBoundingVolume` and an `OctreeTileID`. Previously only `QuadtreeTileID` was supported.
- Added `setOrientedBoundingBox`, `setBoundingRegion`, `setBoundingSphere`, and `setS2CellBoundingVolume` functions to `TileBoundingVolumes`.
These just round out some useful capabilities for working with implicit tiling and `Cesium3DTiles::BoundingVolume` instances.
> Add some new bounding volume related helper functions

- CesiumGeospatial/include/CesiumGeospatial/LocalHorizontalCoordinateSystem.h
Fixes typos in the param names in comments in the LocalHorizontalCoordinateSystem header file
> Fix Typo in param names

- CHANGES.md
- CesiumGltf/include/CesiumGltf/AccessorUtility.h
- CesiumGltf/src/AccessorUtility.cpp
- CesiumGltf/test/TestAccessorUtility.cpp
Depends on #826 so merge that first.
This adds the `PositionAccessorType` typedef to `AccessorUtility.h`, as well as the `getPositionAccessorView` method. Although there's only one possible type of position accessor, it's still helpful to put the construction logic here to avoid duplication in our runtimes.
> Add `PositionAccessorType` to `AccessorUtility.h`

- CHANGES.md
- Cesium3DTilesSelection/src/Tileset.cpp
Fixes performance tests reporting completion times that are a little too early (1 second in some warm cache tests).
Could also fix any bugs in user applications where they use `::computeLoadProgress` to determine loading completion. 
Ex. waiting for loading before taking a screenshot, some parts of the screenshot might not have loaded to final detail
This fixes a bug in the mentioned function, where `this->_workerThreadLoadQueue.size()` is being used to calculate tile completion, but it's always 0, because it is cleared at the end of every `::update_view`. The fix is to use the saved value in `_updateResult`.
Discovered while working on PR #779.
Also relates to PR #733, which has a similar fix. I wouldn't be surprised if this was the original cause, but that PR just happened to fix it …
> Fix Tileset::ComputeLoadProgress incorrectly reporting done, when main thread loading exists

- CHANGES.md
- Cesium3DTilesContent/src/QuantizedMeshLoader.cpp
- Cesium3DTilesContent/test/TestQuantizedMeshLoader.cpp
Before this PR, the glTFs generated from quantized-mesh tiles were technically invalid. Our game engine clients weren't too fussed about these problems, which is why we didn't notice.
Fixed the following problems:
* The `asset.version` field was not set.
* The `byteLength` of the buffers was not set. Most clients just used `cesium.data.size()` anyway.
* The `target` type of the bufferView used to store indices was incorrectly set to `ARRAY_BUFFER` instead of `ELEMENT_ARRAY_BUFFER`.
* The bufferView used to store indices had its `byteStride` property set, which is not allowed.
* The glTF did not have any scenes.
> Fix problems with QuantizedMeshLoader-generated glTFs

- CesiumGltf/generated/include/CesiumGltf/ExtensionKhrDracoMeshCompression.h
- CesiumGltf/generated/include/CesiumGltf/ExtensionMeshPrimitiveKhrMaterialsVariants.h
- tools/generate-classes/glTF.json
After https://github.com/CesiumGS/glTF/pull/65 was merged, the code generator was failing because some of the schema files no longer match the generator configuration. This PR fixes it.
I'm going to merge this immediately because the generator currently doesn't work in main, and these changes are trivial.
> Update generator config to work with updated glTF repo

- CHANGES.md
- CesiumAsync/include/CesiumAsync/AsyncSystem.h
- CesiumAsync/include/CesiumAsync/Future.h
- CesiumAsync/include/CesiumAsync/Impl/QueuedScheduler.h
- CesiumAsync/include/CesiumAsync/SharedFuture.h
- CesiumAsync/src/AsyncSystem.cpp
- CesiumAsync/src/QueuedScheduler.cpp
- CesiumAsync/test/TestAsyncSystem.cpp
Adds a new method, `waitInMainThread`, to `AsyncSystem`. 
Calling `asyncSystem.waitInMainThread(std::move(future))` is similar to calling `future.wait()`. Both wait for the future to resolve or reject, and then either return the value or throw an exception. `waitInMainThread` _also_ continues to dispatch main thread tasks while waiting, however. This means that it is safe to call from the main thread even if the future has `thenInMainThread` continuations. `future.wait()`, on the other hand, is very likely to deadlock in this situation.
> Add AsyncSystem::waitInMainThread

- CMakeLists.txt
- CesiumGltfContent/src/ImageManipulation.cpp
- CesiumGltfReader/CMakeLists.txt
- CesiumGltfReader/src/GltfReader.cpp
- extern/CMakeLists.txt
* Upgrade KTX-Software to v4.3.2. See https://github.com/CesiumGS/KTX-Software/pull/1.
* Use the `ktx` library instead of `ktx_read`. While cesium-native currently only needs the read functionality, by depending on `ktx_read` cesium-native prevents anything that uses cesium-native from bringing in the write functionality. This is because there's no `ktx_write`. The only options are `ktx_read` which is read-only, and `ktx` which includes both. If you try to link against both `ktx` and `ktx_read`, you'll end up with multiply-defined symbols.
* Move the STB image resize implementation code into CesiumGltfReader (instead of CesiumGltfContent). This fixes a weird situation where applications that only depend on `CesiumGltfReader` would get linker errors.
* Disable compilation of the KTX CLI by …
> Improvements to the build process

- CHANGES.md
- CesiumGltf/include/CesiumGltf/AccessorUtility.h
- CesiumGltf/src/AccessorUtility.cpp
- CesiumGltf/test/TestAccessorUtility.cpp
Adds `NormalAccessorType` and `getNormalAccessorView`, similar to https://github.com/CesiumGS/cesium-native/pull/827
> Add `NormalAccessorType` to `AccessorUtility.h`

- CHANGES.md
- CesiumGltfWriter/src/GltfWriter.cpp
- CesiumGltfWriter/test/TestGltfWriter.cpp
Because the GLB format includes its own length as a uint32 field inside itself, it's not possible to create a valid GLB file that is 4GiB or larger. Previously GltfWriter would try, and end up producing an invalid GLB; the length fields would end up being the actual length modulo 2^32. With this PR, GLB creation now fails with an error.
> Don't create an invalid GLB when the buffer is too large.

- tools/generate-classes/glTF.json
Small follow up to https://github.com/CesiumGS/cesium-native/pull/851. Removed `attachTo` for schema files that now have the correct prefix.
> Remove `attachTo` for schema files that already have correct prefix

- CHANGES.md
- CesiumGltf/include/CesiumGltf/AccessorWriter.h
Adds an `AccessorWriter` constructor that takes an `AccessorView`.
This is helpful when you have an `AccessorView` but don't have the underlying `Accessor` or index, like if you're using some of the helper functions in `AccessorUtility`.
> Create AccessorWriter from AccessorView

- .github/workflows/build.yml
- CesiumGltf/test/TestJsonValue.cpp
Fixes macOS build failure in latest merge to main, [here](https://github.com/CesiumGS/cesium-native/actions/runs/8802908193).
Also fixes any other macOS builds that happen to use a runner configured with `Image: macos-14-arm64`.
Configure runner for `macos-12` explicitly, instead of `macos-latest`. When choosing the latest, it could actually choose an arm64 variant, which our unit tests fail on (at least 3 related to narrowing). In addition, even specifying `macos-14` can lead to `macos-14-arm64` being chosen.
After review, and we go this direction, we should write an issue to support the latest builds (14, arm64) on CI.
> Fix unit tests failing for macOS (arm64)

- CHANGES.md
- CesiumGltf/include/CesiumGltf/PropertyType.h
- CesiumGltf/src/PropertyType.cpp
- CesiumGltf/test/TestPropertyType.cpp
Added `getComponentCountFromPropertyType`. It's a bit similar to `getDimensionsFromPropertyType`, but more convenient in certain situations.
> Add `getComponentCountFromPropertyType`

- CMakeLists.txt
Showed up in cesium-unreal as this cmake error...
`CMake Error at cesium-native/CMakeLists.txt:210 (install): install TARGETS given no FRAMEWORK DESTINATION for static library FRAMEWORK target "ktx".`
([link to CI run](https://github.com/CesiumGS/cesium-unreal/actions/runs/8838079866))
Setting FRAMEWORK DESTINATION explicitly seems to fix it.
Also remove previous line that set `PROPERTIES PUBLIC_HEADER` to fix the install. This doesn't seem to be needed anymore as the cmake generation works without it
> Fix cmake issue with KTX and iOS

- CesiumGltfContent/src/ImageManipulation.cpp
- CesiumGltfReader/src/GltfReader.cpp
Certain STB functions (image processing) are implemented in cesium-native libs, but can also conflict with STB implementations in the native client.
This recently happened with cesium-unreal and Unreal Engine 5.4, but can happen with others as well.
One solution to this problem is to move any related functions into an isolated namespace. This is what I've done in this PR. Should have no effect on the functionality of cesium-native, just how it links with other libraries.
> Move stb resize function to `Cesium` namespace

- CHANGES.md
- CesiumGltf/src/Model.cpp
- CesiumGltf/test/TestModel.cpp
Extends `Model::merge` to support the following extensions which were previously unsupported:
- `KHR_texture_basisu`
- `EXT_texture_webp`
- `EXT_mesh_gpu_instancing`
- `CESIUM_primitive_outline`
- `CESIUM_tile_edges`
> Add support for more extensions to `Model::merge`.

- CHANGES.md
- CesiumGltfContent/src/GltfUtilities.cpp
- CesiumGltfContent/test/TestGltfUtilities.cpp
Fixes #862 
This is pretty much the simplest possible approach. When deleting bytes from the buffer, it only deletes multiples of 8 bytes.
> Preserve alignment in GltfUtilities::compactBuffer.

- CesiumGltfReader/src/GltfReader.cpp
The problem: `CesiumGltfReader` always uses `STB_IMAGE_IMPLEMENTATION`. If client application also uses `stb_image`, this results in duplicate symbol link errors.
Moving `stb_image.h` into a namespace does not work because all functions are always defined as `extern "C"`.
(BTW, `stb_image_resize.h` includes quite a few standard headers (`stdint.h`,  `string.h`, `math.h`, etc.). I am pretty sure that including standard headers from a namespace is not allowed in C++)
Solution: to add an option to disable `STB_IMAGE_IMPLEMENTATION`. With this, the problem can be solved as follows:
```
set(CESIUM_NO_STB_IMAGE_IMPLEMENTATION ON)
add_subdirectory(cesium-native)
```
> Gltf Reader: use STB_IMAGE_STATIC to avoid conflicts with other libs

- CHANGES.md
- CesiumUtility/include/CesiumUtility/Uri.h
- CesiumUtility/src/Uri.cpp
- CesiumUtility/test/TestUri.cpp
Adds several new functions to the `Uri` class:
* `unescape`
* `unixPathToUriPath`
* `windowsPathToUriPath`
* `nativePathToUriPath`
* `uriPathToUnixPath`
* `uriPathToWindowsPath`
* `uriPathToNativePath`
> Add new functions to Uri class

- CHANGES.md
- CesiumGltf/src/Model.cpp
- CesiumGltf/test/TestModel.cpp
- CesiumGltfContent/src/GltfUtilities.cpp
- CesiumGltfContent/test/TestGltfUtilities.cpp
- CesiumGltfReader/src/decodeDataUrls.cpp
- CesiumGltfReader/src/decodeMeshOpt.cpp
- CesiumGltfReader/src/dequantizeMeshData.cpp
- CesiumGltfReader/test/TestGltfReader.cpp
`EXT_meshopt_compression` is fun because it is, as far as I'm aware, the only thing other than a regular `bufferView` that can reference a `buffer`. This wasn't being accounted for in a lot of the glTF manipulation code.
From the changelog:
- Added support for the following glTF extensions to `Model::merge`. Previously these extensions could end up broken after merging.
-  ...
- `EXT_meshopt_compression`
- `GltfUtilities::collapseToSingleBuffer` now works correctly even if some of the buffers in the model have a `uri` property and the data at that URI has not yet been loaded. Such buffers are left unmodified.
- `GltfUtilities::collapseToSingleBuffer` now works correctly with bufferViews that have the `EXT_meshopt_compression` extension.
- `GltfUtilities::compactBuffer` now accounts for …
> Various glTF fixes, mostly meshopt related

- CHANGES.md
- CesiumGltfContent/src/GltfUtilities.cpp
I'm working with a model that has tens of thousands of buffers and buffer views and `collapseToSingleBuffer` started to become a bottleneck. I changed the code so that there's only a single pass over buffer views which dramatically speeds things up.
For a model with 34680 buffers and 34680 buffer views it goes from 49796 ms to 47 ms.
> Faster `collapseToSingleBuffer`

- CesiumGltfContent/src/ImageManipulation.cpp
- CesiumGltfReader/src/GltfReader.cpp
[Community contribution](https://github.com/CesiumGS/cesium-native/pull/877) to fix an issue where cesium-native's use of the STB library can conflict with an application's use of it.
STB has more than one implementation that can be defined:
* The community contribution solved a problem with `STB_IMAGE_IMPLEMENTATION`. 
* We solved a similar problem with `STB_IMAGE_RESIZE_IMPLEMENTATION` in #871. 
* I additionally rounded this out by making `STB_IMAGE_WRITE_IMPLEMENTATION` static as well to avoid any similar issues in the future.
> Fix STB library conflicts

- CHANGES.md
- CesiumGltf/include/CesiumGltf/Model.h
- CesiumGltf/src/Model.cpp
- CesiumGltf/test/TestModel.cpp
I found myself needing a function like `forEachPrimitiveInScene` but without drilling into meshes / primitives and just traversing over nodes.
> Added `forEachNodeInScene`

- CHANGES.md
- CesiumGltf/generated/include/CesiumGltf/ExtensionMeshPrimitiveExtStructuralMetadata.h
- CesiumGltf/generated/include/CesiumGltf/FeatureId.h
- CesiumGltf/src/Model.cpp
- CesiumGltf/test/TestModel.cpp
- CesiumGltfReader/generated/src/ExtensionMeshPrimitiveExtStructuralMetadataJsonHandler.h
- CesiumGltfReader/generated/src/FeatureIdJsonHandler.h
- CesiumGltfWriter/generated/src/ModelJsonWriter.cpp
There have been a few corrections to the `EXT_mesh_features` and `EXT_structural_metadata` schemas which affect the generated code.
* https://github.com/CesiumGS/glTF/pull/67
* https://github.com/CesiumGS/glTF/pull/68
> Regenerate glTF schemas for metadata extensions

- CHANGES.md
- extern/CMakeLists.txt
This builds on #891 so merge that first.
This PR moves the Abseil functionality embedded in the s2geometry library into an isolated namespace (`cesium_s2geometry_absl`). This avoids linker errors when packaging an Unreal Engine 5.4 game that includes both the Cesium for Unreal and Pixel Streaming plugins, because the Pixel Streaming plugin also embeds some Abseil code.
Fixes CesiumGS/cesium-unreal#1420
> Move Abseil code in s2geometry to an isolated namespace.

- CHANGES.md
- CesiumGeospatial/include/CesiumGeospatial/GlobeRectangle.h
- CesiumQuantizedMeshTerrain/include/CesiumQuantizedMeshTerrain/LayerWriter.h
- CesiumQuantizedMeshTerrain/src/LayerWriter.cpp
- CesiumQuantizedMeshTerrain/src/QuantizedMeshLoader.cpp
- CesiumQuantizedMeshTerrain/test/TestLayerWriter.cpp
- CesiumRasterOverlays/src/RasterOverlayUtilities.cpp
From the changelog:
- Added `LayerWriter` to the `CesiumQuantizedMeshTerrain` library and namespace.
- The glTF accessor for the texture coordinates created by `RasterOverlayUtilities::createRasterOverlayTextureCoordinates` now have min/max values that accurately reflect the range of values. Previously, the minimum was always set to 0.0 and the maximum to 1.0.
Also:
- Removed an unused struct from `QuantizedMeshLoader.cpp`.
- Fixed incorrect doc comment syntax in `GlobeRectangle.h`.
> Some quantized-mesh related improvements

- CHANGES.md
- Cesium3DTilesWriter/src/SchemaWriter.cpp
- Cesium3DTilesWriter/src/SubtreeWriter.cpp
- Cesium3DTilesWriter/src/TilesetWriter.cpp
- CesiumGltfWriter/src/GltfWriter.cpp
- CesiumGltfWriter/test/TestGltfWriter.cpp
- CesiumJsonReader/include/CesiumJsonReader/JsonReaderOptions.h
- CesiumJsonReader/src/JsonReaderOptions.cpp
- CesiumJsonWriter/include/CesiumJsonWriter/ExtensionWriterContext.h
- CesiumJsonWriter/include/CesiumJsonWriter/JsonWriter.h
- CesiumJsonWriter/include/CesiumJsonWriter/writeJsonExtensions.h
- CesiumJsonWriter/src/ExtensionWriterContext.cpp
- CesiumJsonWriter/src/JsonWriter.cpp
- CesiumQuantizedMeshTerrain/src/LayerWriter.cpp
I'm using some statically-typed glTF extensions that are custom to my application. Previously the code assumed that if an extension wasn't registered it must be a `JsonValue`, which would cause a crash due to a bad `any_cast`. Now statically-typed extensions that haven't been registered are ignored.
> Fixed crash when writing statically-typed glTF extensions that aren't registered

- CHANGES.md
- CesiumGeometry/include/CesiumGeometry/IntersectionTests.h
- CesiumGeometry/src/IntersectionTests.cpp
- CesiumGeometry/test/TestIntersectionTests.cpp
since I promise to [fulfill screen space for cesium unreal](https://community.cesium.com/t/screenspacecontroller-for-cesiumunreal/32267) first I need to support ray ellipsoid for intersection tests.
> add ray ellipsoid for intersection tests

- CesiumGeometry/include/CesiumGeometry/IntersectionTests.h
- CesiumGeometry/src/IntersectionTests.cpp
- CesiumGeometry/test/TestIntersectionTests.cpp
After merging #901, I realized we needed to account for the possibility that radii = 0, leading to a division by 0 error. Completely forgot to think of it, so I've opened this PR with a fix. And some doc tweaks as well
> Add check for ellipsoid radii = 0 in `IntersectionTests`

- Cesium3DTilesContent/src/I3dmToGltfConverter.cpp
- CesiumUtility/include/CesiumUtility/ReferenceCounted.h
Minor fix for uninitialized values, which will produce an error if the build is set up to treat certain warnings as errors, and a fix for a missing include.
> Fix uninitialized value and missing include

- CesiumIonClient/src/fillWithRandomBytes.cpp
Ran into this while working in Cesium for Unity. I'm going to self merge it.
> Add missing header in UWP build.

- ThirdParty.json
All other objects use `version`, this one was written as `versions` (prural).
> Fix typo in ThirdParty.json

- Cesium3DTilesContent/src/BatchTableHierarchyPropertyValues.cpp
- Cesium3DTilesContent/src/BatchTableToGltfStructuralMetadata.cpp
- Cesium3DTilesContent/src/SubtreeAvailability.cpp
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/ViewState.h
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.h
- Cesium3DTilesSelection/src/RasterMappedTo3DTile.cpp
- Cesium3DTilesSelection/src/RasterOverlayCollection.cpp
- Cesium3DTilesSelection/src/RasterOverlayUpsampler.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetContentLoader.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
- CesiumGltf/include/CesiumGltf/PropertyAttributePropertyView.h
- CesiumGltf/include/CesiumGltf/PropertyTablePropertyView.h
- CesiumGltf/include/CesiumGltf/PropertyTexturePropertyView.h
- CesiumGltf/test/TestPropertyAttributePropertyView.cpp
- CesiumGltf/test/TestPropertyAttributeView.cpp
- CesiumGltfReader/src/GltfReader.cpp
- CesiumGltfWriter/src/GltfWriter.cpp
- CesiumRasterOverlays/include/CesiumRasterOverlays/RasterOverlayTileProvider.h
- CesiumRasterOverlays/src/RasterOverlay.cpp
- CesiumUtility/include/CesiumUtility/ReferenceCounted.h
- CesiumUtility/src/Tracing.cpp
A lot of the files that used `CESIUM_ASSERT` (as of #874) were missing the include for the file that actually contains the macro. This would sometimes result in compilation errors.
> Add missing include for `CesiumUtility/Assert.h`

- CHANGES.md
- CesiumGltf/include/CesiumGltf/PropertyType.h
- CesiumGltf/src/PropertyType.cpp
- CesiumGltf/test/TestPropertyType.cpp
This is useful for creating class definitions for `PropertyAttribute` from glTF accessors.
`ClassProperty` uses strings to convey component type, but `AccessorSpec::ComponentType` is an integer. But you can use the new method with `convertPropertyComponentTypeToString` to get the corresponding component type string.
> Add method to convert integer `AccessorSpec::ComponentType` to `PropertyComponentType`

- CHANGES.md
- CesiumGltf/include/CesiumGltf/AccessorWriter.h
Changed `AccessorWriter` constructor to take `std::byte*` instead of `uint8_t*` which matches the `AccessorView` constructor and prevents a compilation error.
> Changed `AccessorWriter` constructor to take `std::byte*` instead of `uint8_t*`

- CHANGES.md
- CesiumGltfContent/src/GltfUtilities.cpp
- package.json
* Bump the version.
* Update the changelog.
* Move a couple of unnecessarily global functions into the anonymous namespace. I just happened to notice this while looking at the changes since last release.
I'm going to insta-merge this. It's a PR just for visibility.
> Prepare v0.38 release

- CHANGES.md
- CesiumGltf/include/CesiumGltf/Model.h
- CesiumGltf/src/Model.cpp
- CesiumGltf/test/TestModel.cpp
- CesiumGltfReader/src/applyKhrTextureTransform.cpp
- CesiumGltfReader/src/decodeDraco.cpp
- CesiumGltfReader/src/decodeMeshOpt.cpp
- CesiumGltfReader/src/dequantizeMeshData.cpp
Adds helper functions for removing extensions from `extensionsUsed` and `extensionsRequired` and fixes a bug where `KHR_texture_transform` wasn't removed in `applyKhrTextureTransform`.
> Add `removeExtensionUsed` and `removeExtensionRequired`

- CHANGES.md
- CesiumGltfReader/include/CesiumGltfReader/GltfReader.h
- CesiumGltfReader/src/GltfReader.cpp
- CesiumGltfReader/test/TestGltfReader.cpp
Adds a new option `resolveExternalImages` to `GltfReaderOptions` so that you can load a glTF without resolving and decoding external images. In my case, I'm using `GltfReader` in a pipeline that doesn't need access to texture data.
> Add `resolveExternalImages` flag to `GltfReaderOptions`

- CHANGES.md
- CesiumGltfWriter/include/CesiumGltfWriter/SchemaWriter.h
- CesiumGltfWriter/src/SchemaWriter.cpp
Adds a serializer for `CesiumGltf::Schema` objects.
This is essentially the same as `Cesium3DTilesWriter::SchemaWriter` but I wasn't sure how to unify them in a simple way...
> Add `CesiumGltfWriter::SchemaWriter`

- CesiumIonClient/include/CesiumIonClient/Library.h
- doc/CMakeLists.txt
A few of the more recent namespaces weren't being generated in the documentation:
> Updates to generate updated HTML documentation

- CHANGES.md
- Cesium3DTilesContent/src/I3dmToGltfConverter.cpp
- CesiumGeospatial/include/CesiumGeospatial/S2CellID.h
- CesiumGltfContent/include/CesiumGltfContent/GltfUtilities.h
- CesiumJsonReader/include/CesiumJsonReader/IJsonHandler.h
- CesiumJsonWriter/include/CesiumJsonWriter/JsonWriter.h
The i3dm converter was repeatedly overwriting the beginning of the new glTF buffer that holds instance transformations.
Resolves #942 
I would like to add a test case for this and am hoping that the user who reported the issue will give their permission to use their test data.
> Fix a bug with instances that have multiple nodes

- CesiumGeospatial/include/CesiumGeospatial/EarthGravitationalModel1996Grid.h
- CesiumGeospatial/src/EarthGravitationalModel1996Grid.cpp
- CesiumGeospatial/test/TestEarthGravitationalModel1996Grid.cpp
This function is - perhaps surprisingly - the only thing in cesium-native that does file I/O (other than via an IAssetAccessor, and other than in the tests). By removing it, we're forcing users to read the WW15MGH.DAC file themselves and provide the  contents as a buffer. It's a slight burden, but not too bad. 
The immediate motivation here is that iOS prior to version 13 doesn't support `ifstream`, so the code removed by this PR won't compile there. Unity supports these older iOS versions, so cesium-unity does as well. This is fixable, but it's tricky, especially if we also want to support UTF-8 filenames on Windows, too. We could use fopen/fread on iOS, but on Windows if we pass a `char*` to those functions, it's treated as the current codepage instead of UTF-8. So we'd have to convert …
> Remove EarthGravitationalModel1996Grid::fromFile

- doc/style-guide.md
Preview: https://github.com/CesiumGS/cesium-native/blob/update-style-guide/doc/style-guide.md
Updated the C++ style guide based on internal discussion. For the most part, this is just documenting conventions that already exist in cesium-native.
> Update C++ style guide

- CHANGES.md
- Cesium3DTilesSelection/src/EmptyRasterOverlayTileProvider.cpp
- Cesium3DTilesSelection/src/EmptyRasterOverlayTileProvider.h
- Cesium3DTilesSelection/src/RasterMappedTo3DTile.cpp
- Cesium3DTilesSelection/src/RasterOverlayCollection.cpp
- Cesium3DTilesSelection/test/TestTilesetContentManager.cpp
- CesiumRasterOverlays/include/CesiumRasterOverlays/RasterOverlayTileProvider.h
- CesiumRasterOverlays/src/QuadtreeRasterOverlayTileProvider.cpp
- CesiumRasterOverlays/src/RasterOverlayTileProvider.cpp
- CesiumRasterOverlays/src/TileMapServiceRasterOverlay.cpp
- CesiumRasterOverlays/test/TestQuadtreeRasterOverlayTileProvider.cpp
Previously, if a raster overlay tile provider ran into an error while loading overlay images (for example, if a WMS server returned an error because it didn't support EPSG:4236), those errors were ignored, and the tileset wouldn't show up at all. This was pretty unhelpful for users, who had no way to learn what was happening except by using the debugger. With this PR:
1. Errors loading raster overlays are logged.
2. Raster overlay failures will no longer stop the geometry tile they're attached to from rendering. Instead, once the image load fails, the geometry tile will simply be rendered without any raster overlay.
> Improve raster overlay error reporting and handling

- CHANGES.md
- CesiumAsync/include/CesiumAsync/Impl/CatchFunction.h
- CesiumAsync/test/TestAsyncSystem.cpp
I noticed while working on CesiumGS/cesium-unreal#1526 that a bug made it impossible (compiler error) to pass a mutable lambda to a `catchImmediately` or `catchInMainThread` function. Mutable lambdas are necessary when you want to `std::move` a captured value elsewhere, because in a non-mutable lambda (the default), all captured parameters are const.
This PR fixes it by adding the missing `mutable` to the wrapper lambdas.
> Support for mutable lambdas in `catch` functions.

- Cesium3DTilesSelection/src/TilesetHeightQuery.cpp
- Cesium3DTilesSelection/test/TestTilesetHeightQueries.cpp
Previously, we rejected the future. Now, we resolve it, and report all heights as having failed to sample. This should be easier for users to deal with because they don't need to handle two different types of errors in their height queries.
> When tileset fails to load, report all heights not sampled

- CMakeLists.txt
- cmake/ezvcpkg/ezvcpkg.cmake
Currently projects using cesium-native set `VCPKG_OVERLAY_PORTS` and `VCPKG_OVERLAY_TRIPLETS` as environment variables. This PR allows you to instead set them as regular CMake variables, like what we do for `VCPKG_TRIPLET`.
@jherico would this be a welcome change to bring back into https://github.com/jherico/ezvcpkg?
> Allow vcpkg overlays to be specified as CMake variables

- Cesium3DTilesSelection/src/TilesetContentManager.cpp
Fixes CesiumGS/cesium-unreal#1529
In #783, I renamed `shouldContinueUpdating` to `mightHaveLatentChildren` in an attempt to be more descriptive about what it actually does. I also implemented what I thought was a very slight tweak to the logic for creating explicit children from latent ones.
Previously, when we called `updateTileContent` on a tile that `mightHaveLatentChildren` (which is all tiles to start), we would give the `TilesetContentLoader` associated with the tile a chance to create explicit children. While looking at this in the above PR, I noted this was a bit dangerous in the case that the tile already has explicit children. It could end up clobbering the existing children, which would be very likely to lead to a hard to debug crash.
Of course, none of our current loaders …
> setMightHaveLatentChildren(false) even if a tile has real children.

- Cesium3DTiles/CMakeLists.txt
- Cesium3DTilesSelection/CMakeLists.txt
- CesiumAsync/CMakeLists.txt
- CesiumGltf/CMakeLists.txt
- CesiumGltfContent/CMakeLists.txt
- CesiumGltfReader/CMakeLists.txt
- CesiumGltfWriter/CMakeLists.txt
- CesiumJsonWriter/CMakeLists.txt
- CesiumQuantizedMeshTerrain/CMakeLists.txt
- CesiumUtility/CMakeLists.txt
I don't think these are needed anymore after the switch to vcpkg
> Remove old `CESIUM_NATIVE_` CMake variables

- .github/workflows/build.yml
The latter is no longer supported by GitHub Actions.
> Run build on macos-15 instead of macos-12.

- CesiumGltfReader/include/CesiumGltfReader/GltfSharedAssetSystem.h
This showed up as a compiler error when building Cesium for Unreal against the latest version of cesium-native in main.
> Schema is a struct not a class.

- CesiumUtility/include/CesiumUtility/JsonValue.h
Because Clang gets upset about this in the cesium-unreal build.
> Eliminate variable shadowing in JsonValue

- CesiumRasterOverlays/include/CesiumRasterOverlays/QuadtreeRasterOverlayTileProvider.h
- CesiumRasterOverlays/include/CesiumRasterOverlays/RasterOverlayTileProvider.h
- CesiumRasterOverlays/src/QuadtreeRasterOverlayTileProvider.cpp
There is currently a cache in the QuadtreeRasterOverlayTileProvider to hopefully prevent the same images from being downloaded multiple times when they're used by multiple different geometry tiles. There is currently a bug that will result in the overlay provider believing that the cache is full when it's not, making the cache eventually all but useless. As mentioned in #958, the issue for this bug, now that we have the SharedAsset system, it makes sense to just get rid of that old cache code and use a SharedAssetDepot instead. That's what this PR is for.
I previously opened this PR with a different branch in #987, but @kring suggested a simpler solution which this branch implements.
> Replace RasterOverlayTileProvider cache with SharedAssetDepot

- CHANGES.md
- CesiumRasterOverlays/src/BingMapsRasterOverlay.cpp
- CesiumRasterOverlays/src/TileMapServiceRasterOverlay.cpp
- CesiumRasterOverlays/src/WebMapServiceRasterOverlay.cpp
- CesiumRasterOverlays/src/WebMapTileServiceRasterOverlay.cpp
- CesiumRasterOverlays/test/TestTileMapServiceRasterOverlay.cpp
Part of the fix for https://github.com/CesiumGS/cesium-unreal/issues/1549. This adds checks for a null `CreditSystem` to the various overlay types.
TMS is the only raster overlay type with unit tests, so that was the only one I was able to verify via test. But the change is similar for the other raster overlay types, so hopefully it's sufficient.
> Add checks for `nullptr` credit system in raster overlays

- .github/workflows/build.yml
Currently, the Doxygen CI task doesn't cache the vcpkg artifacts that are built when configuring the CMake project. This means it rebuilds every single one every time the task is run! We can significantly reduce the time it takes to build documentation by simply adopting the same vcpkg cache that the other CI tasks use. This brings the time it takes to run the Documentation CI task down from [12m 17s](https://github.com/CesiumGS/cesium-native/actions/runs/12005187635/job/33461379227) to [only 32s](https://github.com/CesiumGS/cesium-native/actions/runs/12019704527/job/33507514252)!
In theory, as mentioned in #983, we shouldn't need to build the vcpkg dependencies at all to generate the documentation. But this is an easy first step to reduce the time it takes to run CI without needing to …
> Use vcpkg cache for Doxygen CI task

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/IPrepareRendererResources.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TileLoadResult.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.cpp
- Cesium3DTilesSelection/src/CesiumIonTilesetLoader.h
- Cesium3DTilesSelection/src/EllipsoidTilesetLoader.cpp
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- Cesium3DTilesSelection/src/RasterOverlayUpsampler.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetContentLoader.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
- Cesium3DTilesSelection/src/TilesetSharedAssetSystem.cpp
- Cesium3DTilesSelection/test/TestTilesetContentManager.cpp
- Cesium3DTilesSelection/test/TestTilesetSelectionAlgorithm.cpp
- CesiumAsync/include/CesiumAsync/SharedAssetDepot.h
- CesiumAsync/src/CachingAssetAccessor.cpp
- CesiumAsync/test/TestCacheAssetAccessor.cpp
- CesiumGltfReader/include/CesiumGltfReader/GltfReader.h
- CesiumGltfReader/src/GltfReader.cpp
- CesiumQuantizedMeshTerrain/include/CesiumQuantizedMeshTerrain/QuantizedMeshLoader.h
In addition to what's in the changelog:
- Fixed nullptr pExternalMetadataSchema in default TilesetSharedAssetSystem.
- Fixed a missing check for pExternalMetadataSchema in TilesetSharedAssetSystem (it was accidentally checking for pImage instead)
- Fixed a bug where schema URI relative paths were not resolved to absolute ones before starting the request.
These aren't mentioned in the changelog because they're fixes for a feature that hasn't shipped yet.
The bulk of these changes rework how Cesium ion tokens get refreshed when the expire. Previously, CesiumIonTilesetLoader would manually look for tile content requests returning a 401 error, and would refresh the token and retry the request. But that didn't work well when the tile content referenced external resources, like images and …
> Improve Cesium ion token refresh and fix some small shared asset problems

- CesiumGltf/test/TestPropertyAttributePropertyView.cpp
- CesiumGltf/test/TestPropertyTablePropertyView.cpp
- CesiumGltf/test/TestPropertyTexturePropertyView.cpp
This fixes the std::optional / std::variant related compiler errors that @lilleyse saw on GCC 13.
I was able to reproduce it on v13.1.0 on Ubuntu 22.04 (via WSL2) in the Release configuration, and this change fixed it for me. As far as I can tell, the previous code was valid and this is a GCC bug, but the code was a little unusual before and so the change here is an improvement.
Strangely enough, I can't seem to get it to fail to compile in the same way on the GH Actions `ubuntu-24.04` runner with `CC=gcc-13` and `CXX=g++-13`. But on that runner, after it compiles successfully, one of the tests fails:
```
192: Test command: /home/runner/work/cesium-native/cesium-native/build/CesiumNativeTests/cesium-native-tests "JsonValue::getSafeNumber() returns std::nullopt if narrowing conversion …
```
> Fix compiler error on GCC 13

- Cesium3DTilesContent/include/Cesium3DTilesContent/TileBoundingVolumes.h
In `TileBoundingVolumes`, the functions that now accept an `ellipsoid` parameter were missing a doc comment about the new param. This PR adds the missing comments.
> Add missing ellipsoid `@params` to `TileBoundingVolumes` functions

- CHANGES.md
- Cesium3DTilesContent/test/TestSubtreeAvailability.cpp
- Cesium3DTilesReader/src/SubtreeFileReader.cpp
`SubtreeFileReader` assumed the subtree would be invalid if its binary chunk was missing, which is not necessarily true. As described in the [spec](https://github.com/CesiumGS/3d-tiles/tree/main/specification/ImplicitTiling#subtree-binary-format), subtrees expressed in the binary format can exist without the binary chunk.
This PR fixes that. I also ended up refactoring how subtrees were procedurally created in `TestSubtreeAvailability`, so the diff is relatively large because of my changes there.
> Allow valid binary subtrees to load without requiring a binary chunk

- CHANGES.md
- CesiumGltf/include/CesiumGltf/InstanceAttributeSemantics.h
- CesiumGltf/include/CesiumGltf/VertexAttributeSemantics.h
- CesiumGltf/src/InstanceAttributeSemantics.cpp
- CesiumGltf/src/VertexAttributeSemantics.cpp
From this comment: https://github.com/CesiumGS/cesium-native/pull/959#issuecomment-2392265495
Adds
* `InstanceAttributeSemantics::TRANSLATION`
* `InstanceAttributeSemantics::ROTATION`
* `InstanceAttributeSemantics::SCALE`
* `InstanceAttributeSemantics::FEATURE_ID_n`
* `VertexAttributeSemantics::FEATURE_ID_n`
> Add more attribute semantics

- cmake/detect-vcpkg-triplet.cmake
on macos apple silicon current cmake will turn DETECTED_VCPKG_TRIPLET to unexpected x64-osx. and I found both CMAKE_SYSTEM_PROCESSOR and CMAKE_OSX_ARCHITECTURES is empty. so I add a cmd to determine CMAKE_SYSTEM_PROCESSOR
> Fix triplet auto detected error on macos apple silicon

- .github/workflows/build.yml
This fixes the extremely long macOS build times (when ccache doesn't eliminate most of the compiling) by switching from the macos-15 to the macos-13 runner. The older runner has double the memory, which is why it is so much faster. We were running out of memory and hitting swap on the macos-15 runner.
This PR also configures vcpkg to target macOS 10.15, which is what we target in Cesium for Unreal and Cesium for Unity. Previously, we were targetting 10.15 for cesium-native itself, but all of the vcpkg dependencies targeted whatever the host system was running (15 or, now, 13). The discrepancy caused a large number of linker warnings.
> Switch to macos-13 runner, target macOS 10.15 for vcpkg dependencies

- CHANGES.md
- CesiumAsync/include/CesiumAsync/SharedAssetDepot.h
- CesiumAsync/test/TestSharedAssetDepot.cpp
This is a PR into #1049 so merge that first.
This fixes a problem I noticed while looking at CesiumgS/cesium-unity#540. The `SharedAssetDepot` keeps itself alive until the last asset it manages becomes unreferenced. It does this by maintaining an IntrusivePointer to itself in some situations. The problem is that it can release this reference while the current thread also holds the mutex. This will result in the SharedAssetDepot being destroyed (just) before the mutex is released, which causes undefined behavior (an assert in debug builds, to start).
This PR adds a test to demonstrate the problem. It fixes it by using a helper class to hold a reference to the depot while the mutex is locked, so that the depot always outlives the mutex lock.
> Ensure SharedAssetDepot stays alive while lock is held

- .github/workflows/prod.yml
To fix a failure when publishing production reference docs:
https://github.com/CesiumGS/cesium-native/actions/runs/12576935529/job/35053725492
I've already merged this to the `cesium.com` to confirm it works, so I'm going to merge it to main right away after opening.
> Specify CESIUM_PRODUCTION_DOCS cmake variable correctly.

- doc/footer.html
A simple fix to use the `dark` theme for Mermaid if the user has set a preference for dark mode. Currently, dark mode makes the diagrams unreadable as they remain in the light Mermaid `default` theme.
> Use Mermaid dark theme for dark mode

- .clang-tidy
- Cesium3DTilesContent/test/TestI3dmToGltfConverter.cpp
- CesiumRasterOverlays/test/TestUrlTemplateRasterOverlay.cpp
- CesiumUtility/include/CesiumUtility/Math.h
- CesiumUtility/src/Assert.cpp
* Disable the `modernize-use-std-numbers` clang-tidy rule and go back to using our own PI constant. Fixes CesiumGS/cesium-unreal#1587
* Convert some new test code to use doctest instead of Catch2.
* Add missing `#include <cstdint>` that would only become apparent when building the debug configuration for Unreal Engine.
Once CI is happy with this, I am going to merge it, because it fixes some brokenness in main.
> Fix various build problems and merge conflicts.

- Cesium3DTilesContent/src/BatchTableToGltfStructuralMetadata.cpp
Because it's not supported in Android NDK r25b.
Fixes #1069 (take 2)
> Don't use std::ranges

- .gitignore
- CHANGES.md
- Cesium3DTiles/generated/include/Cesium3DTiles/TilesetSpec.h
- Cesium3DTiles/include/Cesium3DTiles/Tileset.h
- Cesium3DTiles/src/Tileset.cpp
- Cesium3DTiles/test/TestTileset.cpp
- CesiumGltf/test/TestModel.cpp
- tools/generate-classes/3dTiles.json
Added some helper functions to `Cesium3DTiles::Tileset`
* `forEachTile` (similar to `CesiumGltf::Model::forEachNodeInScene`)
* `forEachContent` (similar to `CesiumGltf::Model::forEachPrimitiveInScene`)
* `addExtensionUsed`
* `addExtensionRequired`
* `removeExtensionUsed`
* `removeExtensionRequired`
* `isExtensionUsed`
* `isExtensionRequired`
> Add helper functions to Cesium3DTiles::Tileset

- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.h
- Cesium3DTilesSelection/test/TestLayerJsonTerrainLoader.cpp
This is a PR into #1072.
It bothered me that the URL placeholders (like `{z}`) in the tile URL templates in layer.json were escaped, and then `substituteTemplateParameters` had to deal with this potential escaping. So this is an attempt to avoid that in a fairly simple way: substitute the values into the template URL before treating it as a URL. 
I think this is fairly reasonable. A URL with placeholders is not a valid URL, so don't try to pretend it is. If this looks reasonable to you @azrogers, then I think the changes to `substituteTemplateParameters` to allow escaped placeholders can be reverted.
The other places we were using placeholders in URLs (`UrlTemplateRasterOverlay` and `WebMapTileServiceRasterOverlay`) were already doing this, perhaps accidentally.
> ada-url: Substitute layer.json placeholders before treating as URLs

- Cesium3DTiles/test/TestTileset.cpp
The new use of std::find in TestTileset.cpp  was failing on Fedora 41.
> Add <algorithm> to Cesium3DTiles/test/TestTileset.cpp

- CHANGES.md
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- CesiumRasterOverlays/src/BingMapsRasterOverlay.cpp
- CesiumUtility/include/CesiumUtility/Uri.h
- CesiumUtility/src/Uri.cpp
- CesiumUtility/test/TestUri.cpp
This was causing the Bing Maps overlay to fail to work in Cesium for Unreal, so the first sample level just showed a textureless white terrain and lots of errors.
Also fixed a problem where the `culture` parameter was not actually used correctly, so specifying a Bing culture wouldn't have worked.
And I changed `Uri::toString` to return a `std::string_view` to match most of the other methods, and because it can. This required explicitly turning it into a `std::string` in a few places.
I'm going to merge this for today's release once CI is happy.
> Fix placeholder handling in BingMapsRasterOverlay.

- CHANGES.md
- CesiumIonClient/src/Connection.cpp
> Fix bad construction of `scopes` in Cesium ion authorize URL

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TilesetOptions.h
This property may have done something once upon a time, but it doesn't anymore.
> Remove unused `TilesetOptions::maximumSimultaneousSubtreeLoads`.

- CHANGES.md
- CesiumUtility/src/Uri.cpp
- CesiumUtility/test/TestUri.cpp
`urlHasScheme` checks if a scheme is followed by `://` but just `:` should be allowed too.
For example, `"geopackage:/home/courtyard_imagery.gpkg"` wasn't being parsed correctly. This seems to be a regression from https://github.com/CesiumGS/cesium-native/pull/1072.
> Fix scheme detection in CesiumUtility::Uri

- CesiumAsync/test/ExamplesAsyncSystem.cpp
Noticed a small mistake in an example: `maybeUrl` should be `!maybeUrl`
> ![image](https://github.com/user-attachments/assets/207614e2-766b-4be0-b5c6-8340cfef8f68)
> Fix AsyncSystem example

- CHANGES.md
- CesiumGltfContent/include/CesiumGltfContent/GltfUtilities.h
- CesiumGltfContent/src/GltfUtilities.cpp
- CesiumGltfContent/test/TestGltfUtilities.cpp
By coincidence, I happened to run into the same error while working on unloading external tilesets that a user reported on our forums yesterday: https://community.cesium.com/t/crash-with-google-tiles/38444
The crash is pretty simple. Some copyright strings end with a trailing semicolon - `Google;` being the one I saw. This causes an exception in `parseGltfCopyright`. It goes through the loop correctly once, but continues to loop again, because `end` isn't `npos` - after all, there is a semicolon, implying there's a next entry to read! But when we start the second run through the loop, `start` is pointing at the end of the string, so every value becomes `npos`, or `-1`. Trying to perform a substring between `-1` and `-1 - -1 + 1` gives us an `out_of_range` exception, and we crash.
The fix …
> Fix exception when parsing copyright with trailing semicolon

- CHANGES.md
- CesiumGltfReader/src/dequantizeMeshData.cpp
This looks like a cut-and-paste error, but the result was that geometry that used unsigned byte positions would be approximately doubled in size, and geometry that used signed 16 bit integers would be half size.
Before:
After:
I tried to come up with a test based on the compressed Duck.glb files, but the compressed normals in those files seem kind of random. I had thought that normals in glb files should be already normalized, but that is not the case for the duck files that use mesh quantization.
> Fix conversion functions for KHR_mesh_quantization decompression

- CHANGES.md
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
As noted in this private support thread:
https://community.cesium.com/t/cesium-for-unreal/37135/14
When request headers are specified in TilesetOptions, they're passed to the initial request for the tileset.json / layer.json. But previously, TilesetJsonLoader was not using those request headers for tile content requests. 
Also fixed a crash that occurs if tileset.json has no valid root tile.
I tested this by using https://webhook.site. When you visit it will create a unique URL to which you can make requests. Add a slash to the end of that, and use it as the URL of Tileset. Hit the Edit button in the top-right and set `Content type` to `application/json` and `Content` to:
```
{
"root": {
"boundingVolume": {
"sphere": [0.0,0.0,0.0,10.0]
},
"content": {
"uri": "foo.glb"
}
}
}
```
Let Cesium …
> Pass request headers to tileset.json content requests.

- CHANGES.md
- CesiumGeometry/include/CesiumGeometry/AxisAlignedBox.h
- CesiumGeometry/src/AxisAlignedBox.cpp
- CesiumGeometry/test/TestAxisAlignedBox.cpp
This is just a helper function that I plan to use in #1111. That PR is getting a bit heavy, so I wanted to break it up into more digestible PRs.
> Add `AxisAlignedBox::fromPoints`

- CHANGES.md
- Cesium3DTilesSelection/test/TestTilesetJsonLoader.cpp
- Cesium3DTilesSelection/test/data/ComplexTypes/ComplexTypes.gltf
- Cesium3DTilesSelection/test/data/ComplexTypes/tileset.json
- CesiumGltf/include/CesiumGltf/PropertyTablePropertyView.h
- CesiumGltf/src/PropertyTableView.cpp
- CesiumGltf/test/TestPropertyTablePropertyView.cpp
- CesiumGltf/test/TestPropertyTableView.cpp
Closes CesiumGS/cesium-unreal#1619. When testing with the [ComplexTypes](https://github.com/CesiumGS/3d-tiles-samples/tree/a8d4e1f47fe8c7ffc44e78c5f9b970532f8c8bc2/glTF/EXT_structural_metadata/ComplexTypes) sample tileset in Cesium for Unreal, @j9liu noticed that the handling of variable length string arrays doesn't currently work. It turns out this is actually a problem in Cesium Native, not Unreal, and just somehow went unnoticed until now. The root of the problem is actually fairly simple: the `arrayOffsets` buffer specifies the _indices_ into the `stringOffsets` buffer, but we were treating it as if it was specifying the _byte offsets_ into that buffer. Some tests needed changing to make this work, but it wasn't much in the end. I also added the ComplexTypes sample as a test.
> Fix variable length string array handling in `EXT_structural_metadata`

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/DebugTileStateDatabase.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TilesetViewGroup.h
- Cesium3DTilesSelection/src/DebugTileStateDatabase.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetViewGroup.cpp
- Cesium3DTilesSelection/test/TestTilesetSelectionAlgorithm.cpp
- CesiumUtility/include/CesiumUtility/TreeTraversalState.h
- CesiumUtility/test/TestTreeTraversalState.cpp
This is a PR into #1125. I'm going to merge it myself, this PR is just for visibility.
Prior to #1125, the "last selection state" of each tile was stored in a field on the tile. With #1125, this is no longer viable, because a separate selection state is needed per view group. So, in that PR, I did the obvious thing of storing the selection state in a hash table indexed by `Tile` pointer. That worked fine, but it noticeably slowed down the `updateView` process (by about 20% in my quick tests) because we look up a _lot_ of tile selection states.
This PR replaces the hashtable with a different scheme that requires more careful bookkeeping, but is drastically faster. Selection states are kept in a new class called `TreeTraversalState`, which is a template and not specific to `Tile`. This …
> Multiple Views: Improve performance of selection state tracking

- CMakeLists.txt
- cmake/macros/configure_cesium_library.cmake
Closes #1066. This is a very small change that adds a `CESIUM_CLANG_TIME_TRACE` option to the CMake build process which will add the `-ftime-trace` option to the Clang command line. This option [generates JSON files compatible with the Chrome profiler](https://aras-p.info/blog/2019/01/16/time-trace-timeline-flame-chart-profiler-for-Clang/) for each object compiled. This alone is kinda neat, but it gets particularly useful when we use it in conjunction with [ClangBuildAnalyzer](https://github.com/aras-p/ClangBuildAnalyzer). This will collate all of the individual JSON files and produce a report on the whole build process.
I've [attached a report](https://github.com/user-attachments/files/19391764/report.txt) generated using the following commands:
```
cmake -B build -S . …
```
> Add -ftime-trace option for clang

- CHANGES.md
- CesiumGltfReader/src/GltfReader.cpp
A vsgCs user provided an ASAN log that showed that GltfReader::postprocessGltf() was leaking, and the problem was that release() was called on the unique_ptr pointing to the GltfReaderResult before it was moved. Unless I'm missing some subtlety, it should be fine to do the move and then let the unique_ptr destructor deallocate / destroy that object; that happpens after the lambda body is exited.
> Fix memory leak in GltfReader::postprocessGltf

- CesiumGltf/include/CesiumGltf/PropertyTexturePropertyView.h
After merging #1133, I tried to build Cesium for Unreal with cesium-native's main and got compiler errors caused by the change in `assembleVecNValue` of some `CESIUM_ASSERT`s to `static_assert`s. It would be nice if that invalid execution path were never even compiled, but that does not appear to be the case, and I can't see any obvious way to make it so. So this PR goes back to the runtime assertions.
Here's the complete error with the static_asserts in place:
```
1>F:\cesium\cesium-unreal-samples\Plugins\cesium-unreal\Source\ThirdParty\include\CesiumGltf\PropertyTexturePropertyView.h(144): error C2338: static_assert failed: 'Only vec2s can contain two-byte integer components.'
1>F:\cesium\cesium-unreal-samples\Plugins\cesium-unreal\Source\ThirdParty\include\CesiumGltf\PropertyTextureProp …
```
> Revert to CESIUM_ASSERT instead of static_assert.

- .github/workflows/build.yml
Currently, the clang-tidy CI task is set up to use the latest version of CMake available, for reasons that probably made sense at the time. Unfortunately, CMake just released version 4.0.0, which breaks compatibility with older versions of CMake. This is causing our CI to fail. Explicitly specifying that we want CMake 3.31.6 solves the issue.
> Force CI clang-tidy job to use CMake 3

- CHANGES.md
- Cesium3DTilesContent/src/ImplicitTilingUtilities.cpp
- Cesium3DTilesContent/test/TestImplicitTilingUtilities.cpp
This PR fixes a bug that I unfortunately didn't realize until just now. I assumed that my unit test for `[pi, -pi`] would suffice, but turns out it's a special case that hides the problem!
Previously, the angle range of the root volume was calculated to be `glm::abs(maxAngle - minAngle)`. That works when `maxAngle >= minAngle`. But it doesn't work for `minAngle < maxAngle` cases, **unless** `minAngle = pi` and `maxAngle = -pi`.
For instance, in the below case, the actual range is `3pi / 2`, but the computed range was `pi/2`. The difference between the angles is actually a slice that is taken out of the full circle:
Also, I didn't put this change in the changelog... and that was intentional at first because the original implementation wasn't robust, so I thought to treat it as …
> Fix angle math for implicit tiling of `BoundingCylinderRegion`

- .github/workflows/build.yml
Closes #1149. The Ubuntu 20.04 CI runner will be deprecated on April 15th. This change updates the 20.04 and 22.04 runners to 22.04 and 24.04 respectively.
> Update GitHub CI runner Ubuntu versions

- .github/workflows/build.yml
We're seeing more jobs fail as GitHub rolls out CMake 4.0 more widely.
> Force use of CMake 3 in Documentation and Windows jobs.

- CHANGES.md
- extern/vcpkg/ports/ktx/portfile.cmake
CC CesiumGS/cesium-unreal#1657.
This will break again the next time msys2 removes the particular verisons listed here, but a proper solution to this problem is elusive.
> Fix broken ktx dependency

- CHANGES.md
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
Fixes CesiumGS/cesium-unreal#1660
The assertion failure described in the issue above was caused by the following:
1. A raster overlay was added to a Tileset that employs external tilesets (Google Photorealistic 3D Tiles).
2. Raster overlays are mapped to `Tile` instances before the `Tile` content is loaded. At that time, we have no way of knowing that content might be an external tileset rather than a glTF.
3. When an external tileset is unloaded, we do not clear its raster overlays (I guess because it isn't expected to have any).
4. Prior to this PR, we weren't clearing raster overlays upon loading content and noticing it's not renderable.
As a result, "placeholder" raster overlays added to an external tileset prior to loading it were not released when the `RasterOverlayTileProvider` was …
> Fix crash by clearing raster overlays associated with tiles with non-render content

- Cesium3DTilesSelection/include/Cesium3DTilesSelection/ViewUpdateResult.h
This was needed to compile the `multiple-views` changes in Cesium for Unity. The build step could not resolve the `std::vector<Tile::Pointer>`s in `ViewUpdateResult` unless we included `Tile.h`.
> Include `Tile.h` in `ViewUpdateResult.h`

- CHANGES.md
- Cesium3DTilesWriter/include/Cesium3DTilesWriter/SubtreeWriter.h
- Cesium3DTilesWriter/src/SubtreeWriter.cpp
- Cesium3DTilesWriter/test/TestSubtreeWriter.cpp
- Cesium3DTilesWriter/test/TestTilesetWriter.cpp
- CesiumGltfWriter/include/CesiumGltfWriter/GltfWriter.h
- CesiumGltfWriter/test/TestGltfWriter.cpp
Adds `SubtreeWriter::writeSubtreeBinary` for writing the [subtree binary format](https://github.com/CesiumGS/3d-tiles/tree/main/specification/ImplicitTiling#subtree-binary-format). Previously we only supported writing the JSON format.
> Add `SubtreeWriter::writeSubtreeBinary`

- CHANGES.md
- Cesium3DTilesContent/include/Cesium3DTilesContent/SubtreeAvailability.h
- Cesium3DTilesContent/src/SubtreeAvailability.cpp
- Cesium3DTilesContent/test/TestSubtreeAvailability.cpp
Fixed a bug where `SubtreeAvailability` wasn't updating the `constant` and `bitstream` properties of the `availability` object when converting constant availability to a bitstream.
This meant the subtree wasn't getting updated:
```json
"childSubtreeAvailability": {
"constant": 0
},
```
After this fix it should look like
```json
"childSubtreeAvailability": {
"bitstream": 0
},
```
> Update `constant`/`bitstream` when setting availability

- CHANGES.md
- Cesium3DTilesContent/include/Cesium3DTilesContent/SubtreeAvailability.h
- Cesium3DTilesContent/src/SubtreeAvailability.cpp
- Cesium3DTilesContent/test/TestSubtreeAvailability.cpp
This PR adds `setTilesAvailable` to `SubtreeAvailability::createEmpty`. The default behavior was sufficiently documented (initializing all tiles as available), but a bit unexpected because of the implications of "empty". Either way, it helps to have the option to explicitly set how to initialize the tile availability.
> Add boolean availability parameter in `SubtreeAvailability::createEmpty`

- CHANGES.md
- Cesium3DTilesContent/include/Cesium3DTilesContent/SubtreeAvailability.h
- Cesium3DTilesContent/src/SubtreeAvailability.cpp
- Cesium3DTilesContent/test/TestSubtreeAvailability.cpp
Steps to reproduce
1. Create unavailable subtree
2. Set a tile's availability to true
3. Set a content's availability to true
4. Set a tile's availability to true
5. `undefined behavior`
Step 3 causes `subtree.buffers[0].cesium.data` to grow which invalidates the span held onto by tile availability.
Fixed by updating all the spans when `convertConstantAvailabilityToBitstream` is called so that they point to valid memory.
> Fix use-after-free bug in `SubtreeAvailability`

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tile.h
- Cesium3DTilesSelection/src/EllipsoidTilesetLoader.cpp
- Cesium3DTilesSelection/src/ImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/src/ImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
- Cesium3DTilesSelection/test/TestImplicitOctreeLoader.cpp
- Cesium3DTilesSelection/test/TestImplicitQuadtreeLoader.cpp
- Cesium3DTilesSelection/test/TestTilesetContentManager.cpp
@j9liu found a tileset that was causing reference count assertion errors when clicking "Refresh Tileset" in Cesium for Unreal. The problem essentially boiled down to the fact that the tileset used implicit tiling and some tiles that exist but do not have content, and as a result `ImplicitOctreeLoader` (also quadtree) creates tiles that initially have `TileEmptyContent`. Loaded content (including empty content) "sometimes" counts as a reference against the Tile. In this case, `addReference` was not being called when the tile was initially created with empty content, but `releaseReference` _was_ being called when the tile's content was unloaded. Oops!
This is more complicated than I'd like it to be. Loaded content counts as a `Tile` reference so that we don't destroy the tile before its …
> Fix Tile reference counting assertion with implicit tiling

- CHANGES.md
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
Closes CesiumGS/cesium-unreal#1682. As documented in that issue, when creating a tileset using the `EllipsoidTilesetLoader`, if the tileset has raster overlays, it will crash when unloading. This turns out to be a result of simply forgetting to pass the `LoadedTileEnumerator` to the `RasterOverlayCollection` when using the `TilesetContentManager` constructor that is currently only used by the `EllipsoidTilesetLoader`.
> Fix crash when unloading ellipsoid tileset with raster overlays

- CHANGES.md
- Cesium3DTilesSelection/src/TilesetJsonLoader.cpp
Fixed incorrect handling of legacy maximumLevel property in TilesetJsonLoader.cpp by adding one to availableLevels when implicit loader for it is created.
> Fixed incorrect handling of legacy maximumLevel property in TilesetJsonLoader.cpp

- CHANGES.md
- CesiumGeometry/src/OrientedBoundingBox.cpp
- CesiumGeometry/test/TestOrientedBoundingBox.cpp
Corrected `OrientedBoundingBox::computeDistanceSquaredToPosition()` to account for degenerate half axes. 
- ~[ ] I have updated the documentation as necessary.~
Added unit tests for degenerate axes case.
> OrientedBoundingBox::computeDistanceSquaredToPosition can potentially use degenerate axes

- CesiumCurl/include/CesiumCurl/CurlAssetAccessor.h
- CesiumCurl/src/CurlAssetAccessor.cpp
iOS prior to version 13 is missing `std::filesystem` capabilities used by `CurlAssetAccessor`. It's only used to create directories in PUTs to file URLs, and off by default anyway. So this PR ifdefs out the feature out on older iOS versions in order to make it compile.
> Fix build on iOS prior to v13.

- CesiumCurl/src/CurlAssetAccessor.cpp
When building on MacOS 15.3.1, XCode 16.4 clang 17.0, two warnings are generated (and treated as errors) due to unused functions in `CesiumCurl/src/CurlAssetAccessor.cpp`.  
This PR adds an `#if` block around those functions to exclude them on iOS devices with version < 13.
> Exclude unused functions which triggered a build error on XCode 16, clang 17

- CHANGES.md
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/DebugTileStateDatabase.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tile.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TileLoadRequester.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/TilesetViewGroup.h
- Cesium3DTilesSelection/include/Cesium3DTilesSelection/ViewUpdateResult.h
- Cesium3DTilesSelection/src/DebugTileStateDatabase.cpp
- Cesium3DTilesSelection/src/Tile.cpp
- Cesium3DTilesSelection/src/Tileset.cpp
- Cesium3DTilesSelection/src/TilesetContentManager.cpp
- Cesium3DTilesSelection/src/TilesetHeightQuery.cpp
- Cesium3DTilesSelection/src/TilesetHeightQuery.h
- Cesium3DTilesSelection/src/TilesetViewGroup.cpp
- Cesium3DTilesSelection/test/TestTileLoadRequester.cpp
- Cesium3DTilesSelection/test/TestTilesetSelectionAlgorithm.cpp
- Cesium3DTilesSelection/test/TestTilesetViewGroup.cpp
- CesiumUtility/include/CesiumUtility/IntrusivePointer.h
- CesiumUtility/include/CesiumUtility/TreeTraversalState.h
The `getRootTile` method on `Tileset` returns a pointer to the root tile, once there is one. Previously, the returned pointer would be to const if called on a const Tileset, and to non-const otherwise. After this PR, the returned pointer is _always_ to const.
This is an important improvement because some modifications to `Tile` and the data it holds are unsafe, even when done from the main thread. For example, upsampling for raster overlays happens in a worker thread, which is given a pointer to the parent tile's glTF. The `Tileset` makes sure this is safe, but if users are allowed to make arbitrary modifications to `Tile` while this is happening, then there is potential for undefined behavior. And #1186 introduces another place where a tile's model is read in a background thread. …
> Only provide `const` access to the root tile

- CHANGES.md
- Cesium3DTilesSelection/src/EmptyRasterOverlayTileProvider.cpp
- Cesium3DTilesSelection/src/EmptyRasterOverlayTileProvider.h
- Cesium3DTilesSelection/test/TestTilesetContentManager.cpp
- CesiumRasterOverlays/include/CesiumRasterOverlays/QuadtreeRasterOverlayTileProvider.h
- CesiumRasterOverlays/include/CesiumRasterOverlays/RasterOverlayExternals.h
- CesiumRasterOverlays/include/CesiumRasterOverlays/RasterOverlayTileProvider.h
- CesiumRasterOverlays/src/DebugColorizeTilesRasterOverlay.cpp
- CesiumRasterOverlays/src/GeoJsonDocumentRasterOverlay.cpp
- CesiumRasterOverlays/src/QuadtreeRasterOverlayTileProvider.cpp
- CesiumRasterOverlays/src/RasterOverlay.cpp
- CesiumRasterOverlays/src/RasterOverlayTileProvider.cpp
- CesiumRasterOverlays/src/RasterizedPolygonsOverlay.cpp
This is some light but slightly noisy raster overlay refactoring.
- Added `RasterOverlayExternals` to wrap up all the little interfaces that raster overlays use. I've so far not threaded this throughout the whole system. Mostly because it's pending some other WIP changes.
- `loadTileImage` now receives a const reference to the `RasterOverlayTile`. There's no good reason this method should modify the tile.
- Moved implementations of some `RasterOverlayTileProvider` methods to the .cpp file.
> Add `RasterOverlayExternals`, make `RasterOverlayTileProvider::loadTileImage` receive a const `RasterOverlayTile`

- CesiumRasterOverlays/include/CesiumRasterOverlays/GoogleMapTilesRasterOverlay.h
- CesiumRasterOverlays/src/GoogleMapTilesRasterOverlay.cpp
- CesiumRasterOverlays/src/IonRasterOverlay.cpp
Don't show two Google Maps logos when loading Google Maps via Cesium ion.
> Avoid duplicate Google logo
