CesiumGS/cesium-native

CHANGES.md

Only one entry had been missing

Updated CHANGES.md with a small change

---

CesiumIonClient/src/Connection.cpp

This is acctually for https://github.com/CesiumGS/cesium-unreal/issues/314  - further details added there

Connection error messages

---

CesiumGltf/include/CesiumGltf/ExtensibleObject.h
CesiumGltf/src/ExtensibleObject.cpp

Super tiny PR to clean up the code slightly.
See https://github.com/CesiumGS/cesium-native/pull/208#discussion_r616552593 for background.

Use std::as_const instead of const_cast.

---

CHANGES.md
Cesium3DTiles/src/Tile.cpp

Let tile be renderable if all rasters have ready tiles

---

Cesium3DTiles/src/Tileset.cpp

Add tile to load only if it meets sse and ancestor doesn't

---

CHANGES.md
Cesium3DTiles/src/BingMapsRasterOverlay.cpp

There was some confusion in a previous attempt to implement this, but now I think it works.

Avoid unnecessarily restarting Bing Maps sessions

---

CHANGES.md
CesiumGltfReader/src/decodeDraco.cpp

The asset to reproduce the error can be found in this forum post https://community.cesium.com/t/cesium-ion-data-crashes-in-unreal-engine/13523

Match draco indices to gltf if indices accessor doesn't match with draco

---

.travis.yml
CHANGES.md
CesiumGltfReader/src/GltfReader.cpp

Use stbi_image_free instead of free, update CHANGES.

---

CesiumGeometry/include/CesiumGeometry/clipTriangleAtAxisAlignedThreshold.h
CesiumGeometry/test/TestClipTriangleAtAxisAlignedThreshold.cpp

Add catch test for CesiumGeometry::clipTriangleAtAxisAlignedThreshold. And test cases refer to [https://github.com/CesiumGS/cesium/blob/master/Specs/Core/Intersections2DSpec.js](https://github.com/CesiumGS/cesium/blob/master/Specs/Core/Intersections2DSpec.js).

feat: CesiumGeometry::clipTriangleAtAxisAlignedThreshold add unit test

---

CHANGES.md
CesiumUtility/include/CesiumUtility/Math.h
CesiumUtility/test/TestMath.cpp

Add Math::roundUp and roundDown.

---

CHANGES.md
CesiumAsync/include/CesiumAsync/Future.h
CesiumAsync/include/CesiumAsync/SharedFuture.h
CesiumAsync/test/TestAsyncSystem.cpp

Add `Future::isReady`.

---

CHANGES.md
Cesium3DTilesSelection/src/QuadtreeRasterOverlayTileProvider.cpp

Fixes: https://github.com/CesiumGS/cesium-unreal/issues/623

Fixed Bing credits not being collected

---

CHANGES.md
Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tile.h
Cesium3DTilesSelection/src/Tile.cpp
Cesium3DTilesSelection/src/Tileset.cpp
Cesium3DTilesSelection/test/TestTilesetSelectionAlgorithm.cpp

Fixed external tilesets not loading when frustum culling was disabled

---

CesiumGeospatial/include/CesiumGeospatial/S2CellBoundingVolume.h
CesiumGeospatial/include/CesiumGeospatial/S2CellID.h
CesiumGeospatial/src/S2CellBoundingVolume.cpp
CesiumGeospatial/src/S2CellID.cpp
CesiumGeospatial/test/TestS2CellID.cpp
extern/CMakeLists.txt

This is useful for zooming to an S2 cell, for example, and is need by Cesium for Unreal.
Also rounds out some comments and doc.
I'm going to merge this right away because it's needed to use Cesium for Unreal with the current cesium-native main, but please take a look.

Add ability to compute a GlobeRectangle from an S2 cell

---

CHANGES.md
CesiumGltfReader/src/decodeDraco.cpp

it will fix the issuses "https://github.com/CesiumGS/cesium-native/issues/400"

draco mesh vertices number maybe greater than attribute accessor count

---

CesiumUtility/include/CesiumUtility/Math.h
CesiumUtility/test/TestMath.cpp

port cesium js math improvements

---

CHANGES.md
CesiumUtility/include/CesiumUtility/IntrusivePointer.h
CesiumUtility/test/TestIntrusivePointer.cpp

enable IntrusivePointer to be created from a derived class

---

CHANGES.md
CesiumGltfReader/test/TestGltfReader.cpp
CesiumJsonReader/include/CesiumJsonReader/IntegerJsonHandler.h

Accept double as integer if fractional part is zero

---

CHANGES.md
Cesium3DTilesSelection/src/GltfContent.cpp
Cesium3DTilesSelection/src/QuantizedMeshContent.cpp
Cesium3DTilesSelection/src/SkirtMeshMetadata.cpp
Cesium3DTilesSelection/src/SkirtMeshMetadata.h
Cesium3DTilesSelection/src/upsampleGltfForRasterOverlays.cpp
Cesium3DTilesSelection/test/TestSkirtMeshMetadata.cpp

Exclude skirt vertices from bounds

---

CHANGES.md
Cesium3DTilesSelection/src/ImplicitTraversal.cpp
Cesium3DTilesSelection/src/TilesetLoadTileFromJson.cpp

Fixes https://github.com/CesiumGS/cesium-unreal/issues/766 and https://github.com/CesiumGS/cesium-native/issues/417.

Pass tile transforms to implicit tiles

---

CHANGES.md
Cesium3DTilesSelection/src/Tileset.cpp
CesiumUtility/include/CesiumUtility/ScopeGuard.h
CesiumUtility/test/TestScopeGuard.cpp

fixes #302 
Provide ScopeGuard utility to automatically trigger a function upon exiting the scope

Add scope guard utility

---

CHANGES.md
Cesium3DTilesSelection/include/Cesium3DTilesSelection/CreditSystem.h
Cesium3DTilesSelection/src/CreditSystem.cpp
Cesium3DTilesSelection/test/TestCreditSystem.cpp

Fixes #449
Builds off of the "pass-gltf-copyright" branch because I am testing with credits in the gltf copyright.

Sort credits by frequency

---

CHANGES.md
Cesium3DTilesSelection/include/Cesium3DTilesSelection/CreditSystem.h
Cesium3DTilesSelection/include/Cesium3DTilesSelection/IonRasterOverlay.h
Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterOverlay.h
Cesium3DTilesSelection/include/Cesium3DTilesSelection/TilesetOptions.h
Cesium3DTilesSelection/src/BingMapsRasterOverlay.cpp
Cesium3DTilesSelection/src/CreditSystem.cpp
Cesium3DTilesSelection/src/IonRasterOverlay.cpp
Cesium3DTilesSelection/src/Tile.cpp
Cesium3DTilesSelection/src/TileMapServiceRasterOverlay.cpp
Cesium3DTilesSelection/src/Tileset.cpp
Cesium3DTilesSelection/src/TilesetLoadIonAssetEndpoint.cpp

Part of https://github.com/CesiumGS/cesium-unreal/issues/765

Show onscreen credits

---

.concierge/config.json
.concierge/templates/pullRequestOpened.hbs

This is copied from https://github.com/CesiumGS/cesium-unreal/pull/791

Add concierge config to check first time contributors.

---

ThirdParty.json

This is similar to Cesium for Unreal's ThirdParty json file except for MikkTSpace

Add ThirdParty json file

---

CHANGES.md
Cesium3DTilesSelection/include/Cesium3DTilesSelection/IPrepareRendererResources.h
Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterOverlay.h
Cesium3DTilesSelection/src/RasterOverlayTileProvider.cpp
Cesium3DTilesSelection/test/SimplePrepareRendererResource.h

Native side for the raster overlay renderer options PR (https://github.com/CesiumGS/cesium-unreal/pull/784)

Raster overlay filtering option

---

Cesium3DTilesSelection/include/Cesium3DTilesSelection/WebMapServiceRasterOverlay.h
Cesium3DTilesSelection/src/WebMapServiceRasterOverlay.cpp

a custom RasterOverlay that supports WMS.
-- I have signed the CLA.

add WMS raster overlay

---

CHANGES.md
Cesium3DTilesSelection/src/ImplicitTraversal.cpp
Cesium3DTilesSelection/src/Tile.cpp
Cesium3DTilesSelection/src/upsampleGltfForRasterOverlays.cpp
Cesium3DTilesSelection/src/upsampleGltfForRasterOverlays.h

This pull request should fix the problem described here: https://github.com/CesiumGS/cesium-unreal/issues/840.

Fix terrain holes when using terrain cutout with no other layers

---

ThirdParty.json

This PR updates thirdparty.json to match the new conventions. It also updates the versions of third party libraries used in a handful of cases.

Third party library update

---

Cesium3DTilesSelection/src/Tile.cpp

Fix for missing rectangle for projection

---

CHANGES.md
Cesium3DTilesSelection/src/Tile.cpp

Fixes issue described here: https://github.com/CesiumGS/cesium-unreal/issues/886

Fix crash when copyright string is empty

---

Cesium3DTilesSelection/src/TilesetLoadTilesetDotJson.cpp

There was a blank line in the credit list and it did not look good.

Remove Empty Credit

---

Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterMappedTo3DTile.h
Cesium3DTilesSelection/include/Cesium3DTilesSelection/RasterOverlayCollection.h
Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h
Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
Cesium3DTilesSelection/src/LayerJsonTerrainLoader.h
Cesium3DTilesSelection/src/RasterOverlayCollection.cpp
Cesium3DTilesSelection/src/Tileset.cpp
Cesium3DTilesSelection/src/TilesetContentManager.cpp
Cesium3DTilesSelection/test/TestTilesetContentManager.cpp

This PR is part of the refactor series #481. This addresses the review comments for the following PR:
#516
#521 
#531 
#534

Address PR comments in the refactor branch

---

CHANGES.md
Cesium3DTilesSelection/src/BingMapsRasterOverlay.cpp
Cesium3DTilesSelection/src/IonRasterOverlay.cpp
Cesium3DTilesSelection/src/TileMapServiceRasterOverlay.cpp
Cesium3DTilesSelection/src/WebMapServiceRasterOverlay.cpp

pOwner to Report Error

---

CHANGES.md
Cesium3DTilesSelection/src/TilesetContentManager.cpp

- Update comment to clarify updateDoneState()
- Add CHANGES.md

Update CHANGES.md for refactor loading branch

---

CHANGES.md
Cesium3DTilesSelection/src/CesiumIonTilesetLoader.cpp
Cesium3DTilesSelection/src/CesiumIonTilesetLoader.h
Cesium3DTilesSelection/src/LayerJsonTerrainLoader.cpp
Cesium3DTilesSelection/src/TilesetContentLoaderResult.h
Cesium3DTilesSelection/src/TilesetJsonLoader.cpp

Refresh Token If Expired

---

CHANGES.md
Cesium3DTilesSelection/src/BatchTableToGltfFeatureMetadata.cpp

Fix missing b3dm property values

---

.gitmodules
CHANGES.md
CMakeLists.txt
CesiumAsync/include/CesiumAsync/GunzipAssetAccessor.h
CesiumAsync/src/CachingAssetAccessor.cpp
CesiumAsync/src/GunzipAssetAccessor.cpp
CesiumAsync/test/MockAssetAccessor.h
CesiumAsync/test/MockAssetRequest.h
CesiumAsync/test/MockTaskProcessor.h
CesiumAsync/test/TestCacheAssetAccessor.cpp
CesiumAsync/test/TestGunzipAssetAccessor.cpp
CesiumUtility/CMakeLists.txt
CesiumUtility/include/CesiumUtility/Gunzip.h
CesiumUtility/src/Gunzip.cpp
ThirdParty.json
extern/CMakeLists.txt

Fixes #634
Unreal: https://github.com/CesiumGS/cesium-unreal/pull/1097
Unity: https://github.com/CesiumGS/cesium-unity/pull/323

Automatically unzip data if gzipped data is detected

---

Cesium3DTilesSelection/include/Cesium3DTilesSelection/Tileset.h

It wasn't updated after the major change in #554.

Update doc for Tileset destructor.

---

README.md

Add more detail about generating projects from CMake for use with Visual Studio

Update readme with more CMake / VS build notes

---

CesiumIonClient/include/CesiumIonClient/Connection.h
CesiumIonClient/src/Connection.cpp
CesiumUtility/include/CesiumUtility/Uri.h
CesiumUtility/src/Uri.cpp
CesiumUtility/test/TestGetQueryValue.cpp

Add utility function to extract a value from a URI given a key.

Extract Value From URI

---

CesiumGltf/include/CesiumGltf/PropertyAttributeView.h
CesiumGltf/src/PropertyAttributeView.cpp
CesiumGltf/test/TestPropertyAttributePropertyView.cpp
CesiumGltf/test/TestPropertyAttributeView.cpp

Fixes https://github.com/CesiumGS/cesium-native/issues/758

Remove `uint32_t` support for property attributes

---

CHANGES.md
Cesium3DTilesSelection/test/waitForFuture.h
CesiumIonClient/CMakeLists.txt
CesiumIonClient/include/CesiumIonClient/Connection.h
CesiumIonClient/include/CesiumIonClient/Defaults.h
CesiumIonClient/src/Connection.cpp
CesiumIonClient/src/Response.cpp
CesiumIonClient/test/TestConnection.cpp
CesiumIonClient/test/data/defaults.json
CesiumUtility/include/CesiumUtility/Uri.h
CesiumUtility/src/Uri.cpp
CesiumUtility/test/TestGetQueryValue.cpp

This cherry picks the commits from the following PRs into the v0.27.x branch:
* https://github.com/CesiumGS/cesium-native/pull/744
* https://github.com/CesiumGS/cesium-native/pull/772
* https://github.com/CesiumGS/cesium-native/pull/773
Plus some odds and ends to adapt for other reorg changes that happened in v0.28.x.

Cherry pick CesiumIonClient changes into v0.27.x

---

CHANGES.md
Cesium3DTilesContent/include/Cesium3DTilesContent/TileTransform.h
Cesium3DTilesContent/src/TileTransform.cpp
Cesium3DTilesContent/test/TestTileTransform.cpp

To match the `getTransform` we already had. And add tests and doc for all.

Add TileTransform::setTransform

---

doc/CMakeLists.txt

Add CesiumRasterOverlays  in to the Doc

Add CesiumRasterOverlays  in to the Doc

---

CHANGES.md
CesiumAsync/include/CesiumAsync/Impl/QueuedScheduler.h
CesiumAsync/test/TestAsyncSystem.cpp

Don't hang in waitForMainThread waiting for a future that rejects

---

CHANGES.md
Cesium3DTilesSelection/src/TilesetContentManager.cpp
CesiumGeometry/include/CesiumGeometry/IntersectionTests.h
CesiumGeometry/src/IntersectionTests.cpp
CesiumGeometry/test/TestIntersectionTests.cpp

Fixes #914 
Fixes CesiumGS/cesium-unreal#1461
I should really write some tests for the bounding volume changes...

Fix two bugs with polygon clipping

---

.github/workflows/prod.yml

Generate reference documentation from the cesium.com branch and publish it to the web site

---

CHANGES.md

Only caught this post-merge. Whoops!

Fix changelog entry for #1000

---

doc/topics/async-system.md

Based on feedback and discussion here:
https://github.com/CesiumGS/cesium-native/pull/1012#discussion_r1869975386

Don't describe things as "made up" in the AsyncSystem documentation

---

.github/workflows/prod.yml
doc/CMakeLists.txt
doc/header-noindex.html
doc/header.html

- Use Doxygen 1.12.
- Use ccache and the vcpkg artifacts cache to improve performance.
- Run the doc deploy in both the `cesium.com` and `cesium.com-staging` branches. In the latter, deploy to `cesium-native/ref-doc-staging/` instead of `cesium-native/ref-doc/`. This allows us to test doc changes without affecting production.

Production doc script improvements.

---

CHANGES.md
Cesium3DTilesContent/src/BatchTableToGltfStructuralMetadata.cpp
Cesium3DTilesContent/src/I3dmToGltfConverter.cpp

Error fixes and cleanup for i3dm metadata

---

README.md

With the release of 3D Tiles for Godot - as well as [a user on the forums](https://community.cesium.com/t/cesium-native-dart-package/41196) sharing a Dart package they've created wrapping Cesium Native - I think it's about time we update the list of community projects in the README!

Update projects list in the README

---

CHANGES.md
Cesium3DTilesSelection/src/TilesetHeightQuery.cpp
Cesium3DTilesSelection/test/TestTilesetHeightQueries.cpp

Don't hardcode WGS84 ellipsoid in `TilesetHeightQuery`
